### ISSUE TITLE
[ssr] verify server rendering 

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#1]
My understanding is this should just work, but I haven't verified/explored it yet. Would like to launch v1.0.0 with the ssr story figured out.

https://twitter.com/poke707/status/845252764183683072
https://twitter.com/rauchg/status/845372211321982976

**Comment by Flaque** [comment]
Forgive me if I'm wrong about this, but isn't [vx-demo](https://github.com/hshoff/vx/tree/master/packages/vx-demo) already running server side?

Doesn't Next already do server side rendering as just part of it's process?

**Comment by hshoff** [comment]
> but isn't vx-demo already running server side?

yup!

> doesn't Next already do server side rendering as just part of it's process?

also yup!

there was a react error throwing (maybe it was from a previous version of Next) saying path attributes we're inconsistent. It doesn't look like it does it anymore, which is great. 

I'd like to verify that it works with other SSR projects like https://github.com/airbnb/hypernova for example. I just haven't gotten around to it yet.

**Comment by janek26** [comment]
Newest Version of Next `"next": "^2.3.1"` throws following Warning:

```
warning.js?72da31c:36Warning: React attempted to reuse markup in a container but 
the checksum was invalid.
This generally means that you are using server rendering and the markup generated 
on the server was not what the client was expecting.
React injected new markup to compensate which works but you have lost many of the 
benefits of server rendering.
Instead, figure out why the markup being generated is different on the client or server:
 (client) ="vx-bar" x="13" y="0" width="8" height=
 (server) ="vx-bar" x="13" y="27" width="8" height
```
So its not properly rendering serverside yet.

**Comment by hshoff** [comment]
Yeah something is is up with 2.3.1. vx-demo.now.sh is using [`next@2.2.0`](https://github.com/hshoff/vx/blob/master/packages/vx-demo/package.json#L39) which appears to work without warning right now. I need to dive into the changelog and see what's up.

**Comment by kandros** [comment]
Hi, I would like to dig into this, is there a "must have" checklist to consider?

**Comment by hshoff** [comment]
Seems like this is fine. No reports of problems so far. Going to close for now. Feel free to open a new issue if you run into problems with vx and ssr.
