### ISSUE TITLE
support for interpolation

### ISSUE THREAD

**Issue by chrisdrackett** [hshoff/vx#115]
I wonder if it is currently possible to create a stepped area / line chart (interpolation  value of `step-before` / `step-after`) using VX. If not, might be a nice addition!

**Comment by williaster** [comment]
Hey @chrisdrackett, thanks for your interest in vx!

This _is_ already possible with vx using the `@vx/curve` package, which exports all of the standard d3 interpolators including `curveStep`, `curveStepBefore`, and `curveStepAfter`. You simply pass one of the interpolators (or even roll your own if you like) as the `curve` prop to e.g., the `<LinePath />` or `<AreaClosed />` components from `@vx/shape`.

[Here's an example](https://www.webpackbin.com/bins/-Kr7QFZLWD4g4wmPv4np) you can check out for how to do it.

![image](https://user-images.githubusercontent.com/4496521/29139959-a1e2deb6-7cfd-11e7-82aa-f816323ec391.png)

**Comment by graingert** [comment]
@williaster that example is down now

**Comment by williaster** [comment]
oops, webpackbin is no longer a thing :( 

here's a [new one](https://codesandbox.io/s/o75r0x8v1z).

<img width="500" src="https://user-images.githubusercontent.com/4496521/43854115-cde063d6-9af6-11e8-9ad0-196e4298f492.png" />
