### ISSUE TITLE
[network] @vx/network has not been published to the npm registry

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#117]
It looks like `@vx/network` is not yet published on npm. [See here](https://www.npmjs.com/search?q=@vx/network&page=1&ranking=optimal). Or just try `npm install @vx/network`:

<img width="1050" alt="screen shot 2017-08-12 at 9 15 03 am" src="https://user-images.githubusercontent.com/5942769/29242276-c0107874-7f3e-11e7-853c-f1a93276800a.PNG">

**Comment by hshoff** [comment]
Sorry about that! I've been away on vacation. Just published.
