### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by kandros** [hshoff/vx#128]
Well it sound funny that a project from `Airbnb JavaScript Style Guide creator` doesn't have linting :)

In italy we have a saying
>the shoemaker always wears worn-out shoes

 a reminder that those who carry out a particular profession take care of their clients needs but neglect their own

@hshoff can i proceed adding eslint using airbnb rules?

**Comment by kandros** [comment]
reference #10

**Comment by williaster** [comment]
hey @kandros, thanks for bringing this up. 

we went pretty far down this path already (see discussion [here](https://github.com/hshoff/vx/pull/97#issuecomment-316122706)) and at that time decided that the time wasn't ripe for linting just yet. I believe the plan was to do this sometime around the 1.0 release which we're getting closer to, @hshoff any additional thoughts?

**Comment by hshoff** [comment]
haha yup! we'll add this with v1 release. It's a bit much for right now. Discussion here: https://github.com/hshoff/vx/pull/97#issuecomment-316122706 is still the plan.
