### ISSUE TITLE
Is there a way to add box shadow in Arc??

### ISSUE THREAD

**Issue by hentrymartin** [hshoff/vx#134]
I want to add Box shadow to each arc. is it possible?? Following is my code
`
     <svg
      width={width}
      height={height}>
        <Group
          top={height / 2 + margin.top}
          left={width / 2}>
          <Arc
            data={data}
            pieValue={d => d.value}
            outerRadius={radius - 12}
            innerRadius={radius - 20}
            fill={d => d.data.fill}
            fillOpacity={1}
            cornerRadius={4}
            padAngle={0.04}
          />
        </Group>
      </svg>
`

**Comment by hshoff** [comment]
Hi @hentrymartin, thanks for checking out vx! 

Yes it's possible. Since it's svg you do it a bit differently than using good old `box-shadow`.
Example: https://www.webpackbin.com/bins/-KsOz0YXrjkwZhdvuwr7

```js
      <svg ref={c => this.svg = c} width={width} height={height}>
          // inside your svg create a filter
          <filter id="dropshadow" height="130%"> // <= id is how you reference it
            <feGaussianBlur in="SourceAlpha" stdDeviation="3"/> 
            <feOffset dx="5" dy="5" result="offsetblur"/>
            <feMerge> 
              <feMergeNode/>
              <feMergeNode in="SourceGraphic"/>
            </feMerge>
          </filter>
          <Arc
            style={{ filter: "url(#dropshadow)"}} // <= add it 
// ...
```

more info on svg filters: https://www.w3.org/Graphics/SVG/IG/resources/svgprimer.html#filters
