### ISSUE TITLE
@vx/responsive in Safari desktop (10.1.2)

### ISSUE THREAD

**Issue by sa-mm** [hshoff/vx#135]
Just a quick note that responsive SVGs don't appear to be responsive on the desktop version of Safari. 

See second chart on [this page](https://sassy-sponge.surge.sh). Code [here](https://github.com/sa-mm/vx/blob/master/fcc_bar_chart/components/area_chart.js).

I think the desktop version of Safari has problems with responsive SVGs in general, but I could be wrong.

**Comment by hshoff** [comment]
Hi @sa-mm, thanks for checking out vx! 

I'd recommend using `withParentSize()` from `@vx/responsive` over `<ScaleSvg />`.

```js
import { withParentSize } from '@vx/responsive';

const ResponsiveAreaChart = withParentSize(({ parentWidth, children, ...rest }) => (
  <AreaChart
    width={parentWidth}
    height={parentHeight}
  >
    {children}
  </AreaChart>
));
```

**Comment by sa-mm** [comment]
Thanks! I’ll give that a shot.
