### ISSUE TITLE
About transition or motion

### ISSUE THREAD

**Issue by woaiwodib107** [hshoff/vx#137]
How to use some functions like transition, delay, duration which in d3.js.
I find [nivo](https://github.com/plouc/nivo) use react-motion.
Could I use other libraries like [react-motion](https://github.com/chenglou/react-motion),
[react-move](react-tools/react-move), [react-transition-group](https://github.com/reactjs/react-transition-group) combine with this library

**Comment by hshoff** [comment]
Hi @woaiwodib107, thanks for checking out vx!

Yes, you could use any of libraries you listed to add animation/transitions to your charts. vx is unopinionated about which library you use. No need to increase bundle sizes just so vx can roll its own animation lib.

For more info about the story of animation in vx check out: https://github.com/hshoff/vx/issues/6#issuecomment-316180664
