### ISSUE TITLE
Axis tick text styles don't apply

### ISSUE THREAD

**Issue by Fxlr8** [hshoff/vx#138]
Found this when | tried to style a chart
`tickTextFill` and `tickTextFontFamily` doesn't change anything

UPD: Just looked at axis source code, these props are missing. Are the docs outdated or these props are not implemented yet?

**Comment by hshoff** [comment]
Hi @Fxlr8, thanks for checking out vx! 

Apologies, yes the docs are outdated for this. Sorry for the frustrations. We'll have stable docs for `v1`.

For now, the way you accomplish custom tick labels is you pass in a `tickLabelComponent` that will wrap each tick label. 

Example:

```js
<AxisRight
  // ...
  tickLabelComponent={
    <text dx="0.33em" fill="white" fontSize={8} fillOpacity={0.8} />
  }
/>
```
from: https://viewsource.now.sh/ethereum
source: https://github.com/hshoff/viewsource/blob/master/components/ethereum/chart/Chart.js#L145

In the future, I want to do another pass at the `<Axis />` api. It's currently unintuitive and has a mix of prop patterns (setters + component wrappers). Will likely remove the component wrapper part and consolidate prop setters to a single object like so:

```js
<AxisRight
  tickLabelProps={({ tick, index }) => {
    dx: "0.33em",
    fill: "white",
    fontSize: 8,
    opacity: index % 2 === 0 ? 0.5 : 0.9,
  }}
/>
```

**Comment by Fxlr8** [comment]
Thanks, @hshoff, by the way, how about adding an ability to pass className prop for every structural element of the chart like (ex. for Axis) line, tick, label? Here are two main reasons why you should think about it: 
1. css styles are faster than inline ones

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/142
