### ISSUE TITLE
[brush] add <BrushX /> and <BrushY /> components

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#14]

**Comment by Fxlr8** [comment]
I can help with implementation, I need this feature in my project

**Comment by Fxlr8** [comment]
I am now trying to implement this feature. I was looking for the best practices and I found that Brush, Zoom, and Drag are commonly used together and share the same logic. Purpose of each of them is to change the selected domain. I think it will be a smart decision to create a reusable HOC, which will hold the domain and pass methods for handling dragging, zooming and brushing to the child component. If we keep them separated and have three different wrappers for this features it will be complicated to keep them in sync if they are used on the same chart. What do you think?

**Comment by khipukamayuq** [comment]
@Fxlr8 How's this coming? Exploring vx adoption and these features would definitely be a plus to have available.

**Comment by hshoff** [comment]
getting closer
![vx-brush-progress](https://user-images.githubusercontent.com/339208/38687828-934ad930-3e45-11e8-988b-fc7a6380f8fe.gif)

**Comment by saidkholov** [comment]
Does @vx/brush offer similar functionality? Any docs on how to use it?

**Comment by PascalSenn** [comment]
@hshoff  I like this!
Any update on this? 
Can I be any help?

**Comment by bindai** [comment]
@hshoff fantastic demo！
Any update now? 
Eager to use it!

**Comment by sseira** [comment]
Just want to +1 all the comments that are eager for brush functionality. 
Any updates on this?
