### ISSUE TITLE
Add innerRef prop to components

### ISSUE THREAD

**Issue by dylanmoz** [hshoff/vx#140]
It would be nice to be able to get the underlying ref node for some of the components. For example, for this [line chart](http://dylanmoz.github.io/trello/) I made, I needed to modify `@vx/shape`'s LinePath to take an `innerRef` prop that would then assign it to the path element's `ref`. This way I could gain access to the svg path element, and glean some data from it (`path.getTotalLength()` and `path.getPointAtLength()`) Other libraries that I know of that do something similar are glamorous and styled-components.

Thoughts?

**Comment by hshoff** [comment]
yup will make refs opt-in

**Comment by mdugue** [comment]
since `forwardRef` is part of react nowadays, wouldn't it make sense to change `innerRef` to `ref`?
