### ISSUE TITLE
[events] make it easier to convert event coords to local to svg coords

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#15]
I've got a `localPoint` util that requires a reference to the svg node https://github.com/hshoff/vx/blob/master/packages/vx-event/src/localPoint.js

but I'd like to make this easier to use/remove the boilerplate of converting the brush event coordinates to local coordinates.

**Comment by erikfox** [comment]
Is it safe to assume that this is a prerequisite to #44 ?

**Comment by hshoff** [comment]
@erikfox yes, it would be if we want tooltips to be svg based. 

I'm considering using a react portal outside the svg that would be div based, so we could just use event coords for positioning on on top of the svg. In that case, this wouldn't be a prereq to #44.
