### ISSUE TITLE
Style attributes shouldn't be repeated in an html tag

### ISSUE THREAD

**Issue by blaze33** [hshoff/vx#150]
like here: https://github.com/hshoff/vx/blob/d69c3eba1537dd4f6083400ce3997f7904442c14/packages/vx-legend/src/legends/Legend.js#L60

The behavior is undefined, see https://stackoverflow.com/a/28867244/343834

In my test case, provided styles aren't used.

**Comment by hshoff** [comment]
Good catch, that's a bug. I will fix.
