### ISSUE TITLE
React 16: Error: Can't resolve 'react/lib/React' in '/node_modules/@vx/bounds/node_modules/react-dom/lib'

### ISSUE THREAD

**Issue by denkristoffer** [hshoff/vx#154]
I'm on version 16.0.0-rc.3 of React and ReactDOM, and get the following error from the bounds package when I try to build on [Netlify](https://netlify.com):

`Module not found: Error: Can't resolve 'react/lib/React' in '/opt/build/repo/packages/website/node_modules/@vx/bounds/node_modules/react-dom/lib'`

I'm struggling to figure out what exactly triggers this error, but my best guess so far is that it's caused by the bounds package installing ReactDOM v15.x ?

**Comment by hshoff** [comment]
Oh yes, you're a bit ahead of me. I need to add react 16 support. I'll add this in `v140` hopefully today. Mind using `react` & `react-dom` 15+ until I get the fix out?
