### ISSUE TITLE
Allow custom component for axis label

### ISSUE THREAD

**Issue by bianchimro** [hshoff/vx#160]
I have an use case where I should wrap the actual text for the label of `Axis` component from `@vx/axis` in a different component, something like:

```
  <AxisBottom
          scale={xScale}
          top={chartHeight+margin}
          left={margin}
          label={<EditableText
            config={config} interactionClick={interactionClick} dataKey="slide-title"
            className="chart-text title-text"
          />}
          stroke={'#1b1a1e'}
          tickTextFill={'#1b1a1e'}
   />
```

We could either have a "smarter" label prop on the component (that checks if the passed value is a string or a node) or either pass a different prop (for example "labelComponent" to delegate label rendering)

**Comment by hshoff** [comment]
Ah yes, we had just removed this in https://github.com/hshoff/vx/pull/142 we will add it back, that's a great use case.

**Comment by bianchimro** [comment]
Hi @hshoff and thanks a lot for your quick response and for your great lib.

I noticed that also `tickLabelComponent` was dropped in the same PR. 

Another possible use case that comes to my mind is tooltips. I am using https://github.com/kuy/redux-tooltip that makes it super-easy to trigger a tooltip on any element by wrapping in an `<Origin/>` component. Something like this:

```
import { Origin } from 'redux-tooltip'
const TextOrigin = Origin.wrapBy('text')

class Chart extends React.Component {
  ...
  render() {
    ...
    return <svg width="500" height="500")>
    <AxisBottom
          scale={xScale}
          label={<TextOrigin content="Some tooltip info">Hello</TextOrigin>}
          stroke={'#1b1a1e'}
   />
    </svg>
  }
}
```

This strategy is probably used also by other libs

In general, I think allowing "wrapping" of vx sub-component is potentially very useful, and with the next react major (16) that allows us to [return arrays from render](https://github.com/facebook/react/issues/2127) could be leveraged in the SVG context.

I think that another possible way to provide the same functionality could be adding props like `renderLabel` or `renderTicks`, which expect a function that provides the "wrapped" component props and maybe an helper to render it directly, like: 

```
<AxisBottom
          scale={xScale}
          renderLabel={
              (defaultLabelProps, renderDefaultLabel) => ( 
                  <Origin content="Some tooltip info">{ renderDefaultLabel('Hello') } </Origin>  )    
         }
         ...
   />
```

Just an idea, I'll try to make a quick test ASAP.

**Comment by hshoff** [comment]
closing in favor of https://github.com/hshoff/vx/pull/165
