### ISSUE TITLE
Support additional link types

### ISSUE THREAD

**Issue by techniq** [hshoff/vx#174]
Creating a separate issue to track, mentioned in #172.

It would be nice to support more link types, similar to vega (see [tree example](https://vega.github.io/vega/examples/tree-layout/), [radial tree example](https://vega.github.io/vega/examples/radial-tree-layout/)), such as:

## Orthogonal
- Useful for [brackets](http://bl.ocks.org/jdarling/2503502)
- Another [example](http://bl.ocks.org/goodmami/fd03b250588e1e1143bd)
![image](https://user-images.githubusercontent.com/177476/31474840-486e8d4e-aecb-11e7-94b4-c69f604ba279.png)

![image](https://user-images.githubusercontent.com/177476/31474806-19a3072e-aecb-11e7-9e87-8fadc14a190c.png)
![image](https://user-images.githubusercontent.com/177476/31474784-fc8f4350-aeca-11e7-81ff-14d2de8f55ca.png)

## Curve
- [example](https://bl.ocks.org/mbostock/4600693)
![image](https://user-images.githubusercontent.com/177476/31474770-eb1c3d9e-aeca-11e7-8ed8-64035f75ffff.png)
![image](https://user-images.githubusercontent.com/177476/31474815-28e535ae-aecb-11e7-82d4-81d622fae82e.png)

also possible
## Elbow (45deg)
- [example](https://bl.ocks.org/tlfrd/3dedf0369f7d67843be17961550218d9) 
- useful for annotations / call outs
![image](https://user-images.githubusercontent.com/177476/31474917-b9b7c344-aecb-11e7-9c29-1d5da9b29133.png)

## Implementation
I'm not sure if all of these should be separate components like `LinkHorizontal`, `LinkVertical`, and `LinkRadial` (`LinkHorizontalOrthogonal` ?) or by adding a `type` prop (or something) such as `<LinkHorizontal type="orthogonal" />` where type could be `line`, `diagonal`, `curve`, `orthogonal`, `elbow`, etc.

I took a quick look at how vega supports the different [linkpath](https://github.com/vega/vega-encode/blob/master/src/LinkPath.js) types, which are implemented using simple svg path line/curve commands.  I envisioned doing something similar, and is typically how I see other d3 implementations, although this would break canvas support (d3 [uses](https://github.com/d3/d3-shape/blob/master/src/link/index.js) it's `context` to abstract the canvas/svg from my understanding.  It looks like there is an [open issue](https://github.com/d3/d3-shape/issues/107) on d3-shape to add orthogonal support, but there hasn't been any response to the original request.

Personally I've only ever used svg with d3, so I would be fine with only support svg.  Thinking more about it, I don't see how a react wrapper could produce canvas, except using [react-konva](https://github.com/lavrton/react-konva) or [react art](https://github.com/reactjs/react-art).

**Comment by techniq** [comment]
Looking at d3-shape's [curveStep](https://github.com/d3/d3-shape#curveStep) looks to possibly give us a context-agnostic way to create an orthogonal link.  Some useful examples to visualize other curve types:

- https://bl.ocks.org/d3noob/ced1b9b18bd8192d2c898884033b5529
- http://bl.ocks.org/d3indepth/b6d4845973089bc1012dec1674d3aff8
- https://cemrajc.github.io/d3-curve-comparison/

While curveStep is probably what we would want for an orthogonal link, I could see benefit in curveStepAfter and curveStepBefore.  Not sure if we would also need a separate horizontal vs vertical version.

**Comment by techniq** [comment]
@hshoff: some progress https://codesandbox.io/s/n3w687vmqj

Current using `<LinkStep />`, `<LinkStep before />` and `<LinkStep after />` although I'm not sure how this should be exposed once we have radial examples like in the original comment (`LinkRadialStep`?)

![image](https://user-images.githubusercontent.com/177476/31923580-689fa30a-b849-11e7-9e8f-c61d7431d4a5.png)

![image](https://user-images.githubusercontent.com/177476/31923599-79a31ce0-b849-11e7-80c6-0f37a437e7a6.png)

![image](https://user-images.githubusercontent.com/177476/31923609-82ca9618-b849-11e7-9cb2-ae629ba7a936.png)

**Comment by techniq** [comment]
@hshoff Take a look at https://n3w687vmqj.codesandbox.io/

We now have step, curve, line, and the existing "diagonal" link types for both cartesian and polar layouts and horizontal or vertical orientations.

![image](https://user-images.githubusercontent.com/177476/32140857-097c5f34-bc46-11e7-87ab-75c191975544.png)

![image](https://user-images.githubusercontent.com/177476/32140887-326be22e-bc47-11e7-83db-0af6147bd51c.png)

![image](https://user-images.githubusercontent.com/177476/32140893-477a07d6-bc47-11e7-90a4-18e34bc95b8f.png)

I broke them out as `Link{Layout}{Type}` components, for example `LinkVerticalCurve`, `LinkHorizontalCurve`, and `LinkRadialCurve` similar to our `LinkVertical`, `LinkHorizontal`, and `LinkRadial`.

I'm going to try to find some more time to knock out the `elbow` type, but I'm pretty happy where things are if not.

**Comment by hshoff** [comment]
@techniq wow! looks great, would love to add these to vx

**Comment by techniq** [comment]
I've been buried at work lately but I'll try to get a PR soon.  I started on the elbow type but having trouble getting the math right.  I'll probably wait to implement it until I get a PR for the others out.
