### ISSUE TITLE
Port VX to Vue.js

### ISSUE THREAD

**Issue by ghost** [hshoff/vx#181]
Hi,

Since I'm not really experienced with React.js. I'm planning to port this package to Vue.js, so I was wondering if there's other people interested in this.

**Comment by geekplux** [comment]
me

**Comment by hshoff** [comment]
Nice! go for it. my guess is most folks in the vue world haven't heard of vx since it's react specific, so you might have to start the project and get more folks on board.

Would love to see ember + web component ports as well 😀

**Comment by ellipticaldoor** [comment]
I would like to work on that port, any updates on that?

**Comment by jens-ox** [comment]
I started dabbling with a Vue port today, since nobody seemed to be working on one.

You can find it over at [jens-ox/vue-vx](https://github.com/jens-ox/vue-vx).

I am a somewhat advanced Vue user (still heavily learning), but never worked with React, so bear with me :smile:

**Comment by hshoff** [comment]
Woo! excited to see this happening!

**Comment by MCYouks** [comment]
Hey everyone, any update on this project?

**Comment by dennisadriaans** [comment]
i give it a try: https://github.com/dennisadriaans/visx-vue
