### ISSUE TITLE
[responsive] manually trigger resize 

### ISSUE THREAD

**Issue by techniq** [hshoff/vx#192]
Currently when using [withParentSize](https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/enhancers/withParentSize.js), if the parent changes size NOT from resizing the window (ex. show/hide side drawer that resizes the width of the main content), the width is not recalculated.

Need a way to force the component call `resize()` (based on a prop change, or expose the actual `resize` function to the user).  Maybe if we use a render function (which would be nice), something like...

```jsx
<ParentSize>
{({ parentWidth, parentHeight, resize }) => (
  ...
  <button onClick={resize} />
)}
</ParentSize>
```

or maybe add a `componentWillReceiveProps` to ParentSize and any prop change will cause a resize to be called.  In my case, I have a `drawerWidth` prop that could trigger this.

```jsx
<ParentSize drawerWidth={drawerWidth}>...</ParentSize>
```

**Comment by techniq** [comment]
[react-resize-detector](https://github.com/maslianok/react-resize-detector) looks to support this, although it appears to have an [issue](https://github.com/maslianok/react-resize-detector/issues/11)

**Comment by techniq** [comment]
I think both options sound great. It seems like if you use resize manually
you probably don't want the eventlisteners as well, so maybe we expose a
`disableEventListeners` prop to not wire them up (or call
removeEventListeners if the prop changes)?

**Comment by techniq** [comment]
@hshoff I didn't know if a Mutation Observer would detect it's parents dimensions changing (and thus it's own) or just the contents/attributes/children of an element/component (I've not used Mutation Observers myself yet but have read about them.

**Comment by techniq** [comment]
We could use a [ResizerObserver](https://developers.google.com/web/updates/2016/10/resizeobserver), but it would require a [polyfill](https://github.com/que-etc/resize-observer-polyfill) as it's [not supported](https://caniuse.com/#feat=resizeobserver) on any browser yet

**Comment by techniq** [comment]
See the note at the bottom of the Google Developers article about [polyfilling](https://github.com/WICG/ResizeObserver/issues/3)

<img width="800" alt="screen shot 2017-11-07 at 11 55 36 am" src="https://user-images.githubusercontent.com/177476/32506457-a5fe874c-c3b2-11e7-8572-be3b17255b2a.png">

**Comment by techniq** [comment]
https://twitter.com/yoavweiss/status/928686636895838208

**Comment by techniq** [comment]
fyi, I noticed the [WithParentSize](https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/enhancers/withParentSize.js) HOC doesn't use the new `<ParentSize />` component so it doesn't resize on DOM changes

**Comment by williaster** [comment]
do you think there's still a need for the HOC? or should we deprecate it and just use `<ParentSize />` going forward?
