### ISSUE TITLE
[gradient] support more than 2 stops (to/from)

### ISSUE THREAD

**Issue by techniq** [hshoff/vx#196]
It would be useful to be able to define a `<LinearGradient />` or `<RadialGradient />` with more than 2 stops (`to` / `from`), maybe adding a `steps` prop that takes in an array of `{ color, offset, opacity }` objects, to support things such as threshold gradients / encoding.

A few examples:
- https://codepen.io/beacrea/pen/reywxz?editors=0010
- https://bl.ocks.org/mbostock/3970883
- https://www.visualcinnamon.com/portfolio/baby-spike

**Comment by hshoff** [comment]
Yup just your custom <stop />s as children. https://github.com/hshoff/vx/blob/master/packages/vx-gradient/src/gradients/LinearGradient.js#L54

**Comment by techniq** [comment]
Awe, thanks. I overlooked that
