### ISSUE TITLE
Event handlers on pie charts?

### ISSUE THREAD

**Issue by erosenberg** [hshoff/vx#199]
Hello, just wanted to know if it's possible to add event handlers to pie charts. Essentially, I want a label elsewhere on my page to update when I hover over a specific data set. Is this possible? I can work around it, but it would be nice functionality to have if not there already. #

**Comment by hshoff** [comment]
Hi @erosenberg, thanks for checking out vx! Yes, events on a pie chart are possible. 

![vx-pie-events](https://user-images.githubusercontent.com/339208/32869269-e52822ba-ca2a-11e7-9b92-60a716001fb5.gif)

demo: https://codesandbox.io/s/mjp8lmvop?expanddevtools=1

the important bit:

```js
<Pie
  // ...
  onMouseEnter={data => event => {
    console.log("mouse enter", data.data.letter);
  }}
/>
```

**Comment by erosenberg** [comment]
This worked excellently. Thanks, @hshoff ! Was that that somewhere in the docs and I just missed it?
Also, amazing job on this and thanks again for the speedy response!

**Comment by libnine** [comment]
Any possibility we can get an updated example? I'm trying to do exactly as above but my `onMouseEnter` function can't seem to grab the section it hovers over. Ultimately, i'm trying to implement a tooltip with the underlying data.

Here's a demo: https://codesandbox.io/s/jolly-burnell-uxzh7?file=/src/App.js

**Comment by hshoff** [comment]
@libnine sure thing, here ya go: https://codesandbox.io/s/strange-lehmann-vdoff?file=/src/App.js

**Comment by libnine** [comment]
Thank you so much Harrison!
