### ISSUE TITLE
What is "labelOrientation" in annotation's `LinePath.js` file?

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#20]
LinePath.js has a parameter `labelOrientation = 'horizontal'` that doesn't seem to do anything. Can we remove it? 

EDIT: Also "labelVerticalAlign", and "labelHorizontalAlign" are not used.

**Comment by hshoff** [comment]
Yup, these are TODOs for me.

**Comment by Flaque** [comment]
TODO's to remove or TODO's to do something with them? I can remove them and submit a PR if you'd like.
