### ISSUE TITLE
AreaStack value accessors

### ISSUE THREAD

**Issue by xcoderzach** [hshoff/vx#200]
The `AreaStack` component has a `keys` stack accessor, but not the corresponding `value` accessor.  My data is shaped like:

```
let series = [
  { x: 0, status: { good: 5, ok: 10, bad: 10 },
  ...
]
```

So my `keys` would be `['good', 'ok', 'bad']` but the value accessor needs to be `(d, k) => d.status[k]`.  I can obviously just map over the data and flatten it, but it would be preferrable to just have a `value` accessor.

If this is something you think is useful I'd be happy to PR it 😄

**Comment by hshoff** [comment]
Sounds useful! go for it. Let me know if you run into any troubles with local dev. Happy to help.

**Comment by hshoff** [comment]
Closing this as it should work now. source: https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/AreaStack.js#L61
https://github.com/d3/d3-shape#stack_value
