### ISSUE TITLE
Center an axis (especially bottom x axis) as a boolean prop

### ISSUE THREAD

**Issue by erosenberg** [hshoff/vx#201]
It would be nice to be able to say something like: `verticallyCentered={true}` as a prop on `Axis` to indicate where an axis should start or where a zero line should be.
I know this is achievable via d3/svg but haven't seen any utils to help with that.

**Comment by hshoff** [comment]
Hi @erosenberg, thanks for checking out vx!

One approach would be to update the domain and range for you scale to keep `0` centered. something like:

```js
  const yScale = scaleLinear({
    range: [yMax, 0],
    domain: [-max(data, y), max(data, y)],
    nice: true
  });
```

![screen shot 2017-12-06 at 3 32 04 pm](https://user-images.githubusercontent.com/339208/33683976-a6e0688e-da9a-11e7-9291-bab1f1bf0624.png)

example: https://codesandbox.io/s/5xjokyo6qk
