### ISSUE TITLE
[responsive] <ParentSize /> ResizeObserver polyfill melts on Firefox Quantum

### ISSUE THREAD

**Issue by sw-yx** [hshoff/vx#202]
i just tried https://vx-demo.now.sh/gallery on firefox quantum and something is going badly wrong...

![vxonfirefox](https://user-images.githubusercontent.com/6764957/32999188-8535113c-cd6e-11e7-9423-e35c97f3a9b0.gif)
 

just reporting.

**Comment by hshoff** [comment]
@sw-yx thanks for the heads up! should be fixed now https://vx-demo.now.sh/gallery

![screen shot 2017-12-01 at 4 22 10 pm](https://user-images.githubusercontent.com/339208/33504016-d980d6f6-d6b3-11e7-8db9-e37dd4dee84b.png)
