### ISSUE TITLE
Add onClick prop to Legend component 

### ISSUE THREAD

**Issue by sabarnix** [hshoff/vx#209]
Can we add an onClick prop to Legend component which is invoked with the name/value of the clicked series?

**Comment by hshoff** [comment]
Hi @sabarnix thanks for checking out vx!

Yes absolutely, surprised I forgot to add this. Will add in `v0.0.150`

**Comment by pisharodySrikanth** [comment]
How to do it in the current version?

**Comment by hshoff** [comment]
@pisharodySrikanth see https://vx-demo.now.sh/legends for an example

```jsx
<LegendItem
  onClick={() => {
    alert(`clicked: ${JSON.stringify(label)}`);
  }}
>
```

**Comment by pisharodySrikanth** [comment]
Hey, thanks for the prompt reply. Wondering how I missed that.
