### ISSUE TITLE
Is the `<Axis/>` element not supposed to be accessed?

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#21]
I noticed in the gallery, there's no examples of using `<Axis />`, but plenty of examples of using `<AxisLeft />`, `<AxisRight />`, `<AxisTop />`, `<AxisBottom />`. Those files also are just wrappers on top of `<Axis/>`. 

I'm writing docs for the `@vx/axis` package, should I emphasize that it's best to use the specific axis's?

**Comment by hshoff** [comment]
I'd say for 90% of the cases folks won't need`<Axis />` but it's there if someone does want to use it.
