### ISSUE TITLE
vx/text leaves empty space at bottom due to svg left unremoved after calculating text width

### ISSUE THREAD

**Issue by msathis** [hshoff/vx#218]
https://github.com/hshoff/vx/blob/master/packages/vx-text/src/util/getStringWidth.js#L9

This svg element is left unremoved which adds 300x150 empty space at the bottom of the page.

**Comment by techniq** [comment]
@msathis Good catch.  I leave the `<svg>` element on the page to improve performance (so an element isn't added/removed from the DOM every time we need to measure a word) but hadn't accounted for the default width/height of the element (and hadn't seen the spacing myself).  I hadn't seen the issue myself, but PR #219 should resolve this.
