### ISSUE TITLE
PatternCircles strokeWidth

### ISSUE THREAD

**Issue by OKNoah** [hshoff/vx#221]
I see this example has `strokeWidth` use in the `PatternCircles` component. But can anyone confirm this works?

https://vx-demo.now.sh/static/docs/vx-pattern.html

```js
<PatternCircles
  id="circles"
  height={6}
  width={6}
  stroke={'black'}
  strokeWidth={1}
/>
```

**Comment by hshoff** [comment]
Hi @OKNoah, thanks for checking out vx!

Here's a codesandbox of a working `strokeWidth` on `<PatternCircles />`: 
<img width="572" alt="screen shot 2018-01-05 at 10 47 30 am" src="https://user-images.githubusercontent.com/339208/34616304-e451cdfc-f205-11e7-8a82-adafafec60d3.png">
https://codesandbox.io/s/n9rr21qkrp

**Comment by hshoff** [comment]
Going to close this but feel free to follow up if you have questions or if something isn’t working as expected.

**Comment by OKNoah** [comment]
@hshoff I will give it another go later, thanks.

**Comment by OKNoah** [comment]
@hshoff Indeed it does work, not sure why it didn't before. Is there a way to increase circle diameter? Looking at the code, it's not obvious how.

**Comment by hshoff** [comment]
@OKNoah great! Yup, just increase `radius`, `width`, and `height`.

`width` & `height` define the the area that will be repeated as a pattern. Then the center point for your circle will be `cx = width / 2` and `cy = height / 2`. Here's another example: https://codesandbox.io/s/1z2k2wxk54
