### ISSUE TITLE
Issue with scalePower

### ISSUE THREAD

**Issue by katerineknox** [hshoff/vx#222]
Hi,
I was just trying to use the scalePower function and came across an error.
`TypeError: scale.base is not a function`
Looks like it's trying to set base when it should be using exponent.
Happy to raise a pull request to fix and update the api to use exponent instead - since it's a small change I'm assuming I shouldn't break anything.

**Comment by williaster** [comment]
Hi @katerineknox! Thanks for checking out vx. 

I think you're right that this should be `scale.exponent` as opposed to `.base`. A PR would be fantastic if you're up for it! Agree re the minor api change 👍
