### ISSUE TITLE
Candle stick charts

### ISSUE THREAD

**Issue by bernatfortet** [hshoff/vx#232]
Any support planned for candlestick charts?

**Comment by techniq** [comment]
@bernatfortet Take a look at the [boxplot](https://vx-demo.now.sh/boxplot) demo as well as this [ethereum demo](https://viewsource.now.sh/ethereum/) and [source](https://github.com/hshoff/viewsource/tree/master/components/ethereum/chart)

**Comment by bernatfortet** [comment]
Thanks! I'll look deeper into the examples.
Super cool project btw 👍
