### ISSUE TITLE
Tooltips Bounds to Screen

### ISSUE THREAD

**Issue by manuelrocha88** [hshoff/vx#239]
I'm trying to put some tooltips on my charts. I'm making use of TooltipWithBounds but this only consider the chart svg bounds.

Could you help me on how to get also the Tooltips being inside screen bounds?

If, for some reason the chart is half visible the tooltips will appear inside svg bounds but half the svg is out of the screen bounds.

How to solve this?

**Comment by hshoff** [comment]
Hi @manuelrocha88 thanks for checking out vx!

you should be able to use https://github.com/hshoff/vx/blob/master/packages/vx-bounds/src/enhancers/withBoundingRects.js and pass in the root component that wraps everything on the screen to get the bounds.

**Comment by manuelrocha88** [comment]
@hshoff thanks for the reply, but that only solve the issue of screen bounds. BTW I've solved the issue already and I'm going to push a PR for that. It should solve other people same issue.

**Comment by manuelrocha88** [comment]
@hshoff you have a PR #240 that solve this "issue". That's more an improvement then a fix.

**Comment by hshoff** [comment]
solved by: https://github.com/hshoff/vx/pull/240
