### ISSUE TITLE
Stacked Areas

### ISSUE THREAD

**Issue by bernatfortet** [hshoff/vx#243]
Hi, 

Maybe I'm missing something very simple but I'm not sure how to create a simple stacked area chart like this:
![image](https://user-images.githubusercontent.com/390010/36294280-7c9aaed6-1294-11e8-92f4-8573e4bc73b0.png)

With https://vx-demo.now.sh/stacked-areas there's no white space
And with https://vx-demo.now.sh/streamgraph it goes negative (below horizontal axis)

I but it's a very simple things.
Thanks!

**Comment by hshoff** [comment]
Hi @bernatfortet, here's an example of how to do this with `<AreaStack />`: https://codesandbox.io/s/k3vo8682q7

![screen shot 2018-02-16 at 11 41 22 am](https://user-images.githubusercontent.com/339208/36318615-5b6b4fa2-130e-11e8-881f-4a60632137ec.png)

it's based on: https://bl.ocks.org/mbostock/3020685

main thing to know is

```js
<AreaStack
  // ...
  y0={d => yScale(d[0])}
  y1={d => yScale(d[0] + d[1])}
  // ...
/>
```

**Comment by bernatfortet** [comment]
Thank you so much! Very helpful 👍 

I'm quite new to d3 and it has always felt very intimidating. yScale still feels very cryptic to me.
Do you know of any good intro to it?

**Comment by techniq** [comment]
I have some descent guides under scales here that might help -
https://github.com/techniq/wiki/wiki/d3

**Comment by bernatfortet** [comment]
🙏 Thanks!

**Comment by guillotegg** [comment]
> Hi @bernatfortet, here's an example of how to do this with `<AreaStack />`: https://codesandbox.io/s/k3vo8682q7
> 
> ![screen shot 2018-02-16 at 11 41 22 am](https://user-images.githubusercontent.com/339208/36318615-5b6b4fa2-130e-11e8-881f-4a60632137ec.png)
> 
> it's based on: https://bl.ocks.org/mbostock/3020685
> 
> main thing to know is
> 
> ```js
> <AreaStack
>   // ...
>   y0={d => yScale(d[0])}
>   y1={d => yScale(d[0] + d[1])}
>   // ...
> />
> ```

@hshoff Thanks for sharing! The fill part doesn't work on the example. 
I took is a base and did some updates; https://codesandbox.io/s/inspiring-roman-tur3rr

**Comment by guillotegg** [comment]
@hshoff Thanks for sharing the code pen example! The fill part doesn't work so I took it a base and did some updates just in case! https://codesandbox.io/s/inspiring-roman-tur3rr
