### ISSUE TITLE
'vx/legend' is not in the npm registry

### ISSUE THREAD

**Issue by RosaRomeroGomez** [hshoff/vx#252]
I've been trying to deploy my React application (created with create-react-app) on a Linux machine but I get the following error when I run `npm install`:

```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'vx/legend' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'app'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

It is pretty strange because this does not happen to me when I deploy the application on my Mac local machine. I've been doing some research on the Internet and I also tried to set the registry but it still didn't solve my problem. My last option I guess it is install vx/legend from github but I'm not sure how to do it.

Any help with this?

Thanks!

**Comment by browniefed** [comment]
Use `@vx/legend` not `vx/legend` https://www.npmjs.com/package/@vx/legend

**Comment by RosaRomeroGomez** [comment]
Thank you for your response. I'm already doing that. This is how my package.json looks like and it is driving me crazy. Maybe there is some issue with the @ at the beginning of the name? As I said, I have no issues when I do npm install on my mac but I don't know what's going on with this Linux machine... It doesn't make any sense... Any other ideas?

```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@vx/legend": "^0.0.154",
    "@vx/responsive": "^0.0.158",
    "@vx/scale": "^0.0.153",
    "bootstrap": "^4.0.0",
    "d3": "^4.13.0",
    "ip": "^1.1.5",
    "jquery": "^3.3.1",
    "lodash": "^4.17.4",
    "papaparse": "^4.3.6",
    "react": "^16.2.0",
    "react-bootstrap": "^0.32.1",
    "react-d3-wrap": "^2.2.1",
    "react-dom": "^16.2.0",
    "react-download-link": "^2.1.3",
    "react-dropzone": "^4.2.7",
    "react-icons": "^2.2.7",
    "react-parcoords": "^0.3.0",
    "react-responsive": "^4.0.4",
    "react-scripts": "1.1.0",
    "react-table": "^6.7.6",
    "react-tree-graph": "^3.1.0",
    "react-vis": "^1.8.2",
    "react-vis-force": "^0.3.1",
    "the-footer": "^2.0.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

**Comment by browniefed** [comment]
Odd, have you tried yarn instead of npm? Are you sure you're using the latest NPM on linux?
I only mentioned the @ since if  see the message it's stripping the @ `'vx/legend' is not in the npm registry.`

**Comment by hshoff** [comment]
Hi @RosaRomeroGomez that's odd. What version of npm are you running locally?

**Comment by williaster** [comment]
`Scoped packages can be published and installed as of npm@2` ([source](https://docs.npmjs.com/misc/scope))

**Comment by RosaRomeroGomez** [comment]
@hshoff locally I'm running npm 5.6.0 and it works fine. Good news, I was able to finally solve the issue using yarn 1.5.1 on the linux machine instead of npm (following @browniefed recommendation). Not sure what's going there. I'm running the same version of npm (5.6.0) on the linux machine but definitely, using yarn seems the solution by now.
Thanks to you all!

**Comment by hshoff** [comment]
Happy to hear you got it working!
