### ISSUE TITLE
scaleTime and ticks()

### ISSUE THREAD

**Issue by DarKDinDoN** [hshoff/vx#253]
Hello,

Let's assume the following code :
```js
const xMax = 600
const x = d => d.date

const data = Array(12).fill(1).map((d, i) => ({
  date: +new Date(Date.now() - (i * 3600000)),
  value: Math.round(Math.max(250, Math.random() * 3000)),
}))

const xScale = scaleTime({
  range: [0, xMax],
  domain: extent(data, x),
})

console.log(xScale.ticks()) // array with 11 items
```

The data array is filled with 12 items, but the function "ticks()" return 11 items. Why is that ?
When I use the xScale with a shape (e.g : LinePath), it works well. But when I use an Axis (that uses the ticks() function), it doesn't work as expected.

<img width="758" alt="capture d ecran 2018-03-16 a 14 43 16" src="https://user-images.githubusercontent.com/1687854/37524037-f5dd16da-2928-11e8-998f-7df2903b6226.png">

**Comment by DarKDinDoN** [comment]
Ok, maybe I did not read the documentation carefully enough 😃 
Ticks are approximate.

I would like to display the ticks with at least the very first and the last one. Is it possible ?

Thanks

**Comment by hshoff** [comment]
Hi @DarKDinDoN, here's an example of rendering custom axis ticks with `<AxisBottom />` https://codesandbox.io/s/rrkq83p9x4. hope it helps!

<img width="421" alt="screen shot 2018-03-16 at 1 25 53 pm" src="https://user-images.githubusercontent.com/339208/37535294-a47b71fc-291d-11e8-9e84-e7a7f13a21e1.png">

**Comment by williaster** [comment]
@DarKDinDoN another option if you don't want to define your entire `Axis` component is to pass an array of `tickValues` to `<Axis* />, which is _not_ approximate and [will override the those from `scale.ticks()`](https://github.com/hshoff/vx/blob/master/packages/vx-axis/src/axis/Axis.js#L85)

**Comment by DarKDinDoN** [comment]
Thank you ! 😄
