### ISSUE TITLE
Support edge/link labels

### ISSUE THREAD

**Issue by loopmode** [hshoff/vx#255]
Hi. Not sure what this issue is.. A feature request, a question for help, an offer to contribute..

I need to create a network graph with labeled edges.
So, basically something like your demo https://vx-demo.now.sh/network
But with labels on the edges, as shown in http://bl.ocks.org/jhb/5955887

if this is already possible, I'd love to see an example in the gallery. I'd be willing to actually create one, given some support e.g. via slack/skype/mail to clarify basic questions.

Otherwise, if it's not possible, it would be really awesome if we could do this by specifying an extra `label` property in the links data:
```
links: [
    {source: nodes[0], target: nodes[1], label: 'knows'},
    {source: nodes[1], target: nodes[2], label: 'hates'},
    {source: nodes[2], target: nodes[0], label: 'loves'}
  ]
```

I see that the code uses a `DefaultLink` component, so a `LabeledLink` might be the way to go. 
Will investigate a bit, and maybe I can create a pull request, but I'm completely new to this lib so it'll take at least some onboarding time, and maybe I just don't get it :)

**Comment by hshoff** [comment]
Hi @loopmode, thanks for checking out vx!

Here's an example with labels -- https://codesandbox.io/s/nrj5wr3v5m
<img width="511" alt="screen shot 2018-03-21 at 1 05 49 pm" src="https://user-images.githubusercontent.com/339208/37725129-9da81422-2d08-11e8-8b0a-a5a03d60aed4.png">

**Comment by loopmode** [comment]
Wow, I didn't get back to this for an entire week...
Well, thank you very much @hshoff ! The library is fantastic, really a pleasure to work with!
Thanks for the example!
