### ISSUE TITLE
importing full Lodash library

### ISSUE THREAD

**Issue by Zaitsev** [hshoff/vx#256]
Such import caused full lodash library to be imported 
`import debounce from 'lodash/debounce';`
doing  tree-shaking etc requires special bablel and webpack configs
It is better to use [lodash.debounce](https://www.npmjs.com/package/lodash.debounce) stand-alone library

**Comment by hshoff** [comment]
Oh wait this was intentional https://github.com/hshoff/vx/pull/66
@lencioni is vx doing this right?

**Comment by lencioni** [comment]
I wouldn't expect import from lodash/foo to bring in all of lodash. Can you put together a minimal repro of what you are seeing?

**Comment by hshoff** [comment]
This should be fixed with the new build. https://github.com/hshoff/vx/pull/298/files#diff-945ec5ee113a4a7af5962b7d29372674R46
