### ISSUE TITLE
IE 11 doesn't work with <ParentSize />

### ISSUE THREAD

**Issue by denkristoffer** [hshoff/vx#258]
Hi! :wave:

In IE 11 I'm seeing the error `ReferenceError 'Symbol' is undefined` when using the `<ParentSize />` component. This is the offending code (built with Babel):

```js
try {
  for (var _iterator = entries[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorN {snip}

...
```

So basically something is going on with Babel's replacement for the `for ... of` loop at https://github.com/hshoff/vx/blob/3e41d4fc030bbe5b9c6b5031f2cb210c2e0ae8ee/packages/vx-responsive/src/components/ParentSize.js#L14

Any ideas?

**Comment by klaemo** [comment]
You need to include a `Symbol` polyfill in your site. It's available in [core-js](https://github.com/zloirock/core-js) for example. Alternatively, you could use https://polyfill.io for "automatic" polyfill detection.

**Comment by denkristoffer** [comment]
Aha, interesting. I didn't know that ES had actually added symbols, I figured it was just Babel's naming. I'll just polyfill it then, thanks!

**Comment by ljharb** [comment]
This should be reopened; nobody should be forced to include a Symbol sham (not a shim, because it can't be faithfully polyfilled) just so you can use `for..of` rather than array iteration methods.

**Comment by hshoff** [comment]
one workaround until i release the fix for `<ParentSize />` is to use `withParentSize()` hoc which uses `entries.forEach()` instead of `for..of`: https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/enhancers/withParentSize.js#L21
