### ISSUE TITLE
Suggestion: Change `Axis.AxisBottom` to `Axis.Bottom`

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#26]
For the pre-made axes, would it be better to remove the prefix since they're called with `Axis.*`? 

So:
`Axis.AxisBottom` -> `Axis.Bottom`
`Axis.AxisTop` -> `Axis.Top`
`Axis.AxisLeft` -> `Axis.Left`
`Axis.AxisRight` -> `Axis.Right`

I'm still pretty inexperienced though and can understand if there's something wrong with this.

**Comment by hshoff** [comment]
Odds are good that most folks will use destructoring when they import the respective Axis they need like so:

```js
import { AxisLeft, AxisBottom } from '@vx/axis';

// ...
<AxisLeft />
<AxisBottom />
```

In the gallery examples I'm using package namespaces to help folks identify where things are coming from (it's not necessary, just thought it'd be easier to read):

```js
import Axis from '@vx/axis';
import Shape from '@vx/shape';

// ...
<Axis.AxisLeft />
<Axis.AxisRight />
<Shape.LinePath />
```

if you want smaller builds (building a library, concerned about js size) you can import the component directly:

```js
import AxisLeft from '@vx/axis/axis/AxisLeft';
import AxisBottom from '@vx/axis/axis/AxisBottom';

// ...
<AxisLeft />
<AxisBottom />
```

**Comment by Flaque** [comment]
Ahhhh, okay that makes a lot of sense. :D

**Comment by williaster** [comment]
this is a slightly different topic/I can open another issue, but right now destructuring fails for me on import:

```javascript
import { AxisLeft } from '@vx/axis';
import Axis from '@vx/axis';

// ...
<AxisLeft /> // throws
<Axis.AxisLeft /> // fine
```

I think this is because [named imports are not the same as destructuring](https://github.com/babel/babel-loader/issues/194)? for that to work should we export as variables in addition to the default object?

**Comment by hshoff** [comment]
good catch @williaster, I'll get a fix out today for all packages. 

fix summary:
```js
// instead of
import Axis from '@vx/axis';
<Axis.AxisLeft />

// if you want to namespace the components
import * as Axis from '@vx/axis';
<Axis.AxisLeft />

// even better (don't import unused things)
import { AxisLeft } from '@vx/axis';
<AxisLeft />

// even better for smaller file size (lib authors)
import AxisLeft from '@vx/axis/axis/AxisLeft';
<AxisLeft />
```

**Comment by hshoff** [comment]
fix is here https://github.com/hshoff/vx/pull/29
