### ISSUE TITLE
@vx/axis ticklabelprops dy not working

### ISSUE THREAD

**Issue by maganuk** [hshoff/vx#267]
After update to 0.0.159 or 0.0.160 from 0.0.158, setting the dy in ticklabelprops on the left or right axis doesnt seem to work. 

`tickLabelProps={() => ({
        dy: '-0.4em',
        textAnchor: 'start'
      })}
`

**Comment by hshoff** [comment]
Thanks for the bug report @maganuk! We replaced axis tick labels with `@vx/text` in `v0.0.159`. Looks like we need to update`@vx/text` to support `em/rem` values for `dx/dy`

**Comment by sto3psl** [comment]
I would be happy to come up with a PR for this. The calculation for `em` to `px` should be pretty straightforward with the font size of the `<Text />` element. But for `rem` I'm not quite sure. Would `getComputedStyle(document.documentElement).fontSize` be the correct way? It returns the font size in `px` which should equal `1rem`.

**Comment by techniq** [comment]
@sto3psl based on a [quick search](https://stackoverflow.com/a/42769683/191902) that should work.  Might be better to do this in userland and pass the pixel value to `<Text dy={...} />`?

**Comment by sto3psl** [comment]
@techniq I agree. I think supporting `em` is fine and if one needs `rem` it's not hard to do in userland. There can even be a hint in the docs how to work with `rem`.

**Comment by hshoff** [comment]
This plan sounds good to me

**Comment by hshoff** [comment]
fixed by https://github.com/hshoff/vx/pull/271
