### ISSUE TITLE
linearBand doesn't play with GridColumn

### ISSUE THREAD

**Issue by janbaykara** [hshoff/vx#268]
So I was trying to make gridlines for a `scaleBand` of hours:

```
  // scales
  const xScale = scaleBand({
    range: [0, xMax],
    domain: new Array(24).fill(0).map((_, hr) => hr),
    padding: 0
  })

  // ... later ...

  <GridColumns
    // style={{ transform: `translateY(${dow * dayHeight})`}}
    lineStyle={{ pointerEvents: 'none' }}
    scale={xScale}
    numTicks={24}
    height={dayHeight - marginBottom}
    strokeDasharray='2,2'
    stroke='rgba(97, 65, 251, 0.33)'
  />
```

Nothing is generated. Recognise I can just `.map(hr => <Line from={{ x: xScale(hr)... />`.

However a quick solution could be for vx `scaleBand` to automatically store the `domain` property as `ticks`, since this issue appears for lack of [`d3.scaleBand.ticks`](https://github.com/d3/d3-scale#band-scales) which [`Grid` relies on](https://github.com/hshoff/vx/blob/master/packages/vx-grid/src/grids/Columns.js#L26-L27).

I'm happy to submit a PR if that sounds like an ok solution.

**Comment by hshoff** [comment]
Good catch, @janbaykara! I mentally made a note about this when I was first making `@vx/grid`, meant to get back to this. Happy to accept a PR where grid uses domain when no `scale.ticks` is undefined.
