### ISSUE TITLE
Release / Version Plan

### ISSUE THREAD

**Issue by chrisdrackett** [hshoff/vx#273]
I'm curious what the plan with VX is when it comes to the release or version. Right now we have VX locked to 0.0.160 because patches might contain breaking changes. Are there any plans to move to semver? I understand the project is still maybe somewhat pre-release, but we're finding it stable enough to use in production.

**Comment by hshoff** [comment]
Hi @chrisdrackett, thanks for checking out vx! We're still in pre v1. Need to add interactions. No breaking changes planned right now ([read more](https://github.com/hshoff/vx/issues/156#issuecomment-331318108)). Check out the [road to v1](https://github.com/hshoff/vx/projects/1).

We're getting closer but a bit more work to be done.
