### ISSUE TITLE
Enforce some code formatting and linting

### ISSUE THREAD

**Issue by sto3psl** [hshoff/vx#274]
Since I have done some small contributions to vx I was never quite sure how to format my code or if there are any rules I should follow.

I think it would be really nice to enforce some by tools since no one wants to think about code formatting in 2018. At my company we use [Prettier](https://prettier.io) for formatting and [StandardJS](https://standardjs.com) as linter. Is that something vx should have to make the dev experience better?

I can set something up with pre commit hooks etc if wanted. You probably don't want StandardJS since I saw semis in the code but eslint is fine too.

**Comment by hshoff** [comment]
This is something we would like to have for v1. I'd like to add prettier and follow Airbnb's style guide. Happy to take a look at a PR if your take a swing at it. Going to close this issue in favor of: https://github.com/hshoff/vx/issues/128
