### ISSUE TITLE
AxisRight inside Group

### ISSUE THREAD

**Issue by esetnik** [hshoff/vx#276]
Is there an example of using `<AxisLeft />` in conjunction with `<AxisRight />`? It might also be useful to upgrade the demo https://vx-demo.now.sh/axis to show `<AxisRight />` as well.

When I try to use `<AxisRight />` in the following example it is rendered in the middle of the graph. I'm not sure if this is a bug or incorrect usage on my part.

<img width="1065" alt="screen shot 2018-04-23 at 5 25 52 pm" src="https://user-images.githubusercontent.com/664434/39154692-23a1dbc0-471d-11e8-869c-93b80178d543.png">

Edit: It appears that `<AxisRight />` does not work when specified within a `<Group />`. Example https://codesandbox.io/s/9qlypmz9qy

Note that this is based on the example provided https://github.com/Flaque/vx-tut/blob/d537efd827c76f09bfeaf6643af0bdb4fd1281b5/pages/index.js and used in the [getting started blog post](https://medium.com/vx-code/getting-started-with-vx-1756bb661410)

**Comment by hshoff** [comment]
fixed by https://github.com/hshoff/vx/pull/271 and confirmed fix in https://github.com/hshoff/vx/pull/280
