### ISSUE TITLE
Documentation typo for @vx/axis

### ISSUE THREAD

**Issue by esetnik** [hshoff/vx#278]
https://vx-demo.now.sh/static/docs/vx-axis.html

Name | Default | Type | Description
-- | -- | -- | --
scale |   | function | A d3 scale function.
top |   | number | A pixel value for the top margin.
left |   | number | A pixel value for the top margin.

Both `top` and `left` descriptions mention the top margin.

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/281
