### ISSUE TITLE
Documentation under source control

### ISSUE THREAD

**Issue by esetnik** [hshoff/vx#279]
I've found a few documentation issues so far while working on the project e.g. https://github.com/hshoff/vx/issues/278. I'd be happy to submit PRs with fixes if the documentation is under source control.

**Comment by sto3psl** [comment]
Hi @esetnik and thanks for the issue. The documentation is actually in this repository. The typo you mentioned in #278 can be found here: [`/packages/vx-demo/static/docs/vx-axis.html`](https://github.com/hshoff/vx/blob/master/packages/vx-demo/static/docs/vx-axis.html). Most (if not all) of the things you find on the website related to docs are in `/packages/vx-demo`.

**Comment by hshoff** [comment]
yup `npm run docs` compiles each package's README into an HTML doc with the same name inside a folder called docs inside vx-demo. Related PR: https://github.com/hshoff/vx/pull/32

I need to run the script and deploy a new vx-demo.now.sh to sync readme updates.

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/281
