### ISSUE TITLE
BarStack With Negative Values

### ISSUE THREAD

**Issue by esetnik** [hshoff/vx#291]
How can I use `<BarStack>` when one of the keys contains negative values?

I am trying to reproduce something that looks like:
<img width="697" alt="screen shot 2018-05-17 at 12 19 34 am" src="https://user-images.githubusercontent.com/664434/40156527-06d3d900-5968-11e8-8bcf-452d9744fd00.png">

Here's a [sandbox link](https://codesandbox.io/s/omk0j0j2z) which demonstrates my attempt at making the [demo](https://vx-demo.now.sh/barstack) work with negative temperatures, but it doesn't seem to work properly.

**Comment by hshoff** [comment]
My fault, I don't think this is documented anywhere yet. Will add an example to gallery as well. But you need to use `<Stack />` and pass in an offset prop `offset={'diverging'}` ([d3 stack offset docs](https://github.com/d3/d3-shape#stack-offsets))

Here's a quick example based of your sandbox:
![screen shot 2018-05-17 at 11 31 02 am](https://user-images.githubusercontent.com/339208/40187570-d366aca6-59c5-11e8-8b7f-d1a5a52adcd4.png)


https://codesandbox.io/s/2pxzozmrlp

**Comment by esetnik** [comment]
That’s great thanks for the clarification!

**Comment by jackal-scratch** [comment]
I think this example stopped working after version 0.0.181 of @vx/shape. Do you have an updated example? thanks!

**Comment by jackal-scratch** [comment]
It seems BarStack is still not able to handle negative values in the latest version. The example provided back in 2018 seems to be broken if using the latest version. Would you happen to have an updated example for BarStack with negative values?

**Comment by nikhilknoldus** [comment]
Were you able to get something? @jackal-scratch @hshoff  ?

**Comment by pat-schoeps** [comment]
I am also struggling with getting the BarStack component to work with negative values, it seems to calculate the position of the stack as if all values are positive, resulting in the column incorrectly shifting down.

**Comment by williaster** [comment]
`offset={'diverging'}` should still be sufficient

**Comment by Mohdaqib18** [comment]
@hshoff This code seems to be written with @vx, which has been deprecated. I am trying to understand how to translate this to current APIs for <Stack/> with @visx; could you help by sharing an updated version?
