### ISSUE TITLE
Warning upon first tooltip mouseover

### ISSUE THREAD

**Issue by marksiano** [hshoff/vx#296]
Upon mousing over an element which creates a tooltip for the first time, a warning is logged in the console.

"Warning: React does not recognize the `getRects` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `getrects` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

This happens with the example too.

**Comment by williaster** [comment]
Hey @marksiano, thanks for checking out vx!

Just curious what version of `@vx/tooltip` you are on and which demo example? This should have been fixed by #290 and in `v0.0.163`

**Comment by marksiano** [comment]
Hi, thanks. This was resolved when I installed the new version.
