### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined with React 16

### ISSUE THREAD

**Issue by marksiano** [hshoff/vx#299]
I just upgraded my project to React 16, and I get this error whenever I try to run it: 

> TypeError: Cannot read property 'object' of undefined with React 16

. It seems to be an issue with vx/axis, since the file at the bottom of the stack trace is ./node_modules/@vx/axis/build/axis/Axis.js.Object.defineProperty.value.

**Comment by hshoff** [comment]
Hi @marksiano could you provide us with a codesandbox link reproducing the error? What are you using to build the project? All of the [gallery](https://vx-demo.now.sh/gallery) examples are running on React 16 without error.

This may be related to the breaking changes between 15 => 16 https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes 

> The deprecations introduced in 15.x have been removed from the core package. React.createClass is now available as create-react-class, React.PropTypes as prop-types, React.DOM as react-dom-factories, react-addons-test-utils as react-dom/test-utils, and shallow renderer as react-test-renderer/shallow. See 15.5.0 and 15.6.0 blog posts for instructions on migrating code and automated codemods.

**Comment by hshoff** [comment]
@marksiano any luck resolving the error?

**Comment by hshoff** [comment]
Going to close this for now. Feel free to follow up and we can reopen if it's found to be a problem with vx. Happy to help!
