### ISSUE TITLE
Add the Natural Earth projection to the  vx-geo package

### ISSUE THREAD

**Issue by JacquiManzi** [hshoff/vx#305]
I found myself needing to use the Natural Earth projection from `d3-geo` and thought it would be a nice addition to the `vx-geo` package.

Here is the pull request: https://github.com/hshoff/vx/pull/304

I compiled and tested this with the vx-demo package. Here is the result:
<img width="862" alt="screen shot 2018-06-09 at 11 26 58 am" src="https://user-images.githubusercontent.com/4119615/41194986-c45aad2c-6bd9-11e8-8817-b4065b736ffd.png">

**Comment by hshoff** [comment]
added in https://github.com/hshoff/vx/pull/304
