### ISSUE TITLE
[docs] @vx/stats shows @vx/boxplot page instead

### ISSUE THREAD

**Issue by jpmn** [hshoff/vx#323]
In the docs, looking at the page for `@vx/stats` shows the page for `@vx/boxplot` instead.

https://vx-demo.now.sh/static/docs/vx-stats.html
https://vx-demo.now.sh/static/docs/vx-boxplot.html

**Comment by hshoff** [comment]
Thanks for the catching this @jpmn! will be fixed in `v0.0.170` release
