### ISSUE TITLE
Can you add event handlers to a VX linegraph?

### ISSUE THREAD

**Issue by kevinxia787** [hshoff/vx#328]

**Comment by hshoff** [comment]
yup! 

```js
onClick={data => event => console.log('click')}
```

**Comment by kevinxia787** [comment]
@hshoff Thanks for the quick reply! Is there a way to isolate the point that I click on? Because if I do 

`onClick={data => event => console.log(data)}
`
I get the data array used to plot the line, not the specific entry.

**Comment by hshoff** [comment]
Ah I see, it takes a bit more work to make that work on a LinePath. Check out this tutorial from @browniefed and the tooltip section for mapping an event position to a data point https://codedaily.io/tutorials/39/Make-a-Beautiful-Interactive-Bitcoin-Price-Chart-with-React-D3-and-VX#Tooltip-Handler

**Comment by Achilles718611** [comment]
It doesn't work in recent vx version.

![image](https://user-images.githubusercontent.com/31845458/58066690-fe2de700-7bbc-11e9-8551-27b7c1b0870f.png)

**Comment by hshoff** [comment]
@Achilles718611 Correct, there was a breaking change in [v0.0.181](https://github.com/hshoff/vx/releases/tag/v0.0.181) for details please see: https://github.com/hshoff/vx/pull/383

```diff
-  onClick={data => event => this._handleLineSelect(event)}
+  onClick={event => this._handleLineSelect(event)}
```

**Comment by Achilles718611** [comment]
Thanks for your kind reply.
But I have to pass data in click event.

**Comment by hshoff** [comment]
`data` is defined in the outer scope so it's still available to use in your event handlers:

```jsx
<LinePath
  data={data[key]}
  // ...
  onClick={event => {
    console.log('my data', data[key]);
    this._handleLineSelect(event);
  }}
/>
```

**Comment by Achilles718611** [comment]
data is object which is consist of key and value(array).
So data[key] is array.
I would like to pass one element of array.
When I use 0.0.179, it's possible.
d => event => {
  .....
}
In 0.0.179 d is what I want to pass value.

**Comment by hshoff** [comment]
Here's an example of how to accomplish this: https://codesandbox.io/s/bitcoinchart-syeeo?fontsize=14&module=%2Fsrc%2FApp.js

**Comment by Achilles718611** [comment]
Got it.
Thank you.
