### ISSUE TITLE
Is it possible to fill above and below two AreaClosed?

### ISSUE THREAD

**Issue by kevinxia787** [hshoff/vx#333]
![example](https://user-images.githubusercontent.com/22988323/44040676-dc27774e-9ee9-11e8-8c61-89b4f6e9a7f6.png)

I have two AreaClosed components like so: https://pastebin.com/i7Dh5ZTQ

Is there a way to fill in between the black lines? I've tried @vx/threshold but that didn't seem to work. 

threshold code: https://pastebin.com/cmySkwwV

Thanks!

**Comment by williaster** [comment]
Hey @kevinxia787 this is easiest to do with the the `Threshold` component. I can't quite tell from your code snippet (code sandbox might be easier?) but to me it looks like you might have your selectors inverted? 

`y0` is typically the minimum value while `y1` is the max
![image](https://user-images.githubusercontent.com/4496521/44045725-4402c974-9ede-11e8-9dfe-8acfa6c7abbe.png)

Without seeing the axes limits, I'm also unsure if the `clipAboveTo={0}` would be doing anything funny here (e.g., if `yMin` actually goes below `0`)

Anyway, I'd start by reversing the `y0`/`y1` selector, and if that doesn't work if you could move it to a codesandbox for reproducibility we can dig in more.

**Comment by kevinxia787** [comment]
Hey @williaster, thanks for responding.

I swapped `y0/y1` just now, and this is what it looks like.
![example1](https://user-images.githubusercontent.com/22988323/44046678-339bdf5a-9efa-11e8-808a-353a3a4f33d1.png)

I won't be able to put the code in the codesandbox but I posted just the graph's code in a pastebin here: https://pastebin.com/JgeTTDck

For some reason when I'm using threshold it only shows the bound above the line, and not below; belowAreaProps and aboveAreaProps also color the same region. Hope the pastebin helps diagnose my issue.

Thanks!!

**Comment by kevinxia787** [comment]
Hi @hshoff, thanks for your response.

Yes, I'm looking for something like that, except the area closed serves as an error range from low to high with a line in the middle like this:
![desired](https://user-images.githubusercontent.com/22988323/44146375-422208e2-a05d-11e8-9333-04abba786baa.png)

This is what I have right now after I modified the code according to the codesandbox.
![current](https://user-images.githubusercontent.com/22988323/44146396-55a468e2-a05d-11e8-937e-d8a40b931e4c.png)


Pastebin: https://pastebin.com/NEugh3Cb

Not sure why the second line isn't drawing - could it be due to the scales I'm using?

**Comment by hshoff** [comment]
I can take a closer look later, but for now you can drop the `- 80 - 40 * Math.random()` I just added that for demo purposes

**Comment by kevinxia787** [comment]
Hi @hsoff, any update on why the y0 line doesn't render? Thanks!

**Comment by hshoff** [comment]
Could you make a codesandbox reproducing thr issue? it’s hard to tell from code alone

**Comment by hshoff** [comment]
here's it working with the brush: https://codesandbox.io/s/j7znj5okj5

the problem was the argument to `withBrush`

so instead of 

```js
ReactDom.render(withBrush(<App />))
```

do

```js
const Demo = withBrush(App);
ReactDOM.render(<Demo />)
```

**Comment by kevinxia787** [comment]
In my code  (not in the sandbox) I'm exporting the graph like so:

`export default withBrush(LineGraph)`

I tried doing:

` const Demo = withBrush(TestGraph);
`
` export default Demo; 
` 

but that didn't work.

**Comment by hshoff** [comment]
Without more details it's hard to say what the problem might be. Is there an error in the console?

**Comment by kevinxia787** [comment]
Yes, only one: 
![error](https://user-images.githubusercontent.com/22988323/44345383-38692d00-a461-11e8-914f-3560e4d79b2e.png)

**Comment by hshoff** [comment]
looks like something related to your scales or x/y accessors

**Comment by kevinxia787** [comment]
Interesting - my original dataset had min and max error like this {minError: 200, maxError: 400}

I got a new dataset with min and max error structured liek this {minError: ["200"], maxError: ["400"]}, and modified my accessors like this: 

`const minSelector = d => Number(d.minError[0]);`

and it worked!

The original accessor was just:

`const minSelector = d => d.minError;`

Any idea why that is? I'm still relatively new to vx/d3.

Thanks so much for your help!

**Comment by hshoff** [comment]
Happy to hear it works now. 

vx is a collection of primitives so it tries not do any magic or guessing about how your data is formatted.

With your new dataset you went from having numbers to arrays of strings. So `d.minError[0]` gets the string then `Number(d.minError[0])` casts your string into a number. 

Your y scale has a domain based on numbers (`[0, max]`). scales map a domain of values to a range of values. You call your scale with a value within our domain and it returns a value within your range. Since your y scale domain is based on a numbers, when your dataset format changed you were passing an array (`d.minError = ["200"]`) to your scale. This probably meant the scale was returning `NaN` (not a number). 

When you see a path d attribute have `NaN` present it is usually an indication that your scales/accessors aren't being called with values they expect. 

Hope that helps!
