### ISSUE TITLE
Circle with mouse events

### ISSUE THREAD

**Issue by trebor** [hshoff/vx#334]
**\<Bar\>** permits me to attach event handlers to it.  How would I do this in the same kind of way for a circle?

a **\<GlyphCircle\>** doesn't appear to be it, it's sizing uses some magic math and I can't figure out how to make some well-defined number of pixels in across. :(

a  **\<Group\>** doesn't appear to be it, i don't appear to be able to attach event handlers to it. :(

More generally the documentation is so thin, that i spent a lot of time digging around in code.  For example, where in doc does it say which components take event handlers?

**Comment by hshoff** [comment]
are you using Circle from @vx/glyph? if so, it’s onClick={data => event => { // stuff }}

but you can also use svg circle: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle

**Comment by trebor** [comment]
Oh, forgive me - I didn't preview my markdown. The components in question are now clearly shown in the original message.  I would rather use the **same** mechanism to capture events throughout my code, so using raw SVG elements is all good and well, but if I mix pure SVG and VX components together, the event capture methods are gonna differ.  Also at that point I am starting ot wonder if the VX is buying me much.

...and for a **\<GlyphCircle\>**, how would i make one of those that is 20px across?

To move on with life I am currently using a **\<Bar\>** with **rx** and **ry**  to circle it up for me, but I am not sure that "squares that look round" are gonna make it past my reviewers. :)

**Comment by hshoff** [comment]
`@vx/glyph` follows d3-shape's symbol api: https://github.com/d3/d3-shape#symbol_size. The size prop is the area. `size={400}` would be 20px wide. 

> but if I mix pure SVG and VX components together, the event capture methods are gonna differ.

This will change in the future (before v1) so vx and svg/react elements will have the same event handlers.

I'd recommend to just use a `<circle />` if you're not doing anything too magical.

**Comment by hshoff** [comment]
@trebor just checking in, were you able to move forward?

**Comment by trebor** [comment]
The **\<Bar\>** has been working for me.  It sizes in an uncomplicated way and accepts events like other things.

**Comment by hshoff** [comment]
sounds good!
