### ISSUE TITLE
Can't call setState (or forceUpdate) on an unmounted component.

### ISSUE THREAD

**Issue by drcmda** [hshoff/vx#336]
Full message:

Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ParentSize (created by ItemList)

This seems to happen because of https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/components/ParentSize.js#L18 The component lives inside a transition that removes it conditionally, the raf probably comes a single frame too late.

I think the best way around it would be to track mounted state in componentDidMount/componentWillUnmount: https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html , and then checking for it before doing setState.

**Comment by hshoff** [comment]
so https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/components/ParentSize.js#L18 was just merged in yesterday but hasn't been published yet (https://github.com/hshoff/vx/pull/335).

Which version of `@vx/responsive` are you using? also which browser and version do you see this? and finally, do you have a repro of the bug so I can ensure that this gets fixed? (no worries if not)

**Comment by drcmda** [comment]
Oops, i was just browsing the code looking for what could've caused it, but setState in a raf will definitively crash transitiongroup. My dependencies are quite outdated atm: "@vx/responsive": "0.0.158"

**Comment by hshoff** [comment]
I'll add a is mounted guard around the setState call in the raf version and publish it in 0.0.172 and we can see if that fixes it for the transitiongroup case.

**Comment by hshoff** [comment]
v0.0.172 is published: https://github.com/hshoff/vx/releases/tag/v0.0.172

@drcmda would you mind updating your `@vx/responsive` dep to this version and seeing if the warning is still present?

**Comment by JacquiManzi** [comment]
Upgrading `@vx/responsive` fixed the warning message for me.

**Comment by hshoff** [comment]
@JacquiManzi thanks for following up @JacquiManzi!

Going to close this issue as it appears resolved. @drcmda happy to re-open if you find it did not fix for your use case.

**Comment by drcmda** [comment]
@hshoff thanks! it looks like it's fixed!
