### ISSUE TITLE
@vx/text innerRef prop

### ISSUE THREAD

**Issue by martensm** [hshoff/vx#338]
I need to access the rendered element's `ref` for the `<Text>` component. This is currently a showstopper for me using this in an application I'm writing. Would you be able to add support for this?

I can submit a PR but I'm not entirely sure what best approach for this would be or if this isn't a good idea for some reason. The `ref` could be added to the `<svg>`, `<text>` or maybe even both elements?

It appears `innerRef` props were added in 0955af66 but not for this component.

**Comment by loopmode** [comment]
Hi. What I am doing is this: just put a regular ref around the vx components, at a place you control (e.g. `<g ref={ref => this.el = ref}>...</g>`), then use `el.querySelector` to get to what I need.
Could it help your case too?

**Comment by hshoff** [comment]
@martensm for now a work around is to pass a `ref` prop on your `<Text />`. Example: https://codesandbox.io/s/94w4pzz0r

For consistency we'll add `innerRef` prop to `@vx/text` in the future.

**Comment by martensm** [comment]
Sorry, I should have been a bit more clear in the original comment. I need a `ref` to a real DOM node, not a React component so I'm not sure that will work unless I'm missing something here.

@loopmode's workaround should be sufficient so I could use that in the meantime.

**Comment by hshoff** [comment]
The work around I mentioned will give you a reference to the `<text/>` react component instance not the dom element. The fix in #339 will give you a ref to the svg dom element that contains the text.

**Comment by martensm** [comment]
Perfect! Thanks for the really quick turnaround time.
