### ISSUE TITLE
patterns for spacing labels

### ISSUE THREAD

**Issue by dagda1** [hshoff/vx#344]
If you look at the picture below, the bottom nodes are all squashed together making the text unreadable:

enter image description here

This seems a common problem and I am curious to know what techniques there are to make these labels more readable.

How can i work out the text width and adjust the circles and rects accordingly?

![hierarrchy](https://user-images.githubusercontent.com/118328/44999460-56807280-afb5-11e8-8f68-cc235c6b4181.png)

**Comment by hshoff** [comment]
A `<Cluster />` accepts an optional [`nodeComponent` prop](https://github.com/hshoff/vx/blob/master/packages/vx-demo/pages/dendrograms.js#L129). Your nodeComponent will get passed a [prop called `node`](https://github.com/hshoff/vx/blob/master/packages/vx-demo/pages/dendrograms.js#L50) for each node in the tree. Here is where you can control the text and the shapes for each node. 

In the demo tile we use a regular svg `<text />`: https://github.com/hshoff/vx/blob/master/packages/vx-demo/pages/dendrograms.js#L74. To make working with text in svg easier, I would recommend taking a look at `@vx/text`: https://vx-demo.now.sh/text

Hope that helps get you started and thanks for checking out vx!
