### ISSUE TITLE
why are other svgs nested in the ouptut

### ISSUE THREAD

**Issue by dagda1** [hshoff/vx#352]
The output of `<Text />` from `@vx/text` is:

`<svg x="0" y="0" style="overflow: visible;"><text class="node-vertical__text" width="50" fill="white" x="0" y="0" text-anchor="middle" style="pointer-events: none;"><tspan x="0" dy="0.71em">General</tspan><tspan x="0" dy="1em">Accounting</tspan></text></svg>`

The external svg is not necessary.  Why is it included?

**Comment by williaster** [comment]
hey @dagda1 thanks for checking out vx! 

@techniq is probably best prepared to answer this one. But I would say that nested svgs are not an invalid DOM structure, and my guess would be that they actually are necessary to get the correct offset positions.

**Comment by sto3psl** [comment]
Hi @dagda1, the additional svg is indeed intentional. AS  @williaster already said it is used to correctly position the `<Text />` component.

For more information and how we got to this solution you can read the discussion in this PR https://github.com/hshoff/vx/pull/271

**Comment by dagda1** [comment]
Thanks for the info!
