### ISSUE TITLE
Is it possible to stack 2 <text /> elements on top of each other

### ISSUE THREAD

**Issue by dagda1** [hshoff/vx#353]
I would like to do this:

```
      <g ref={this.gRef} className={styles.container}>
        <path ref={this.pathRef} />
        <Text
          className={styles.item__name}
          width={50}
          verticalAnchor="start"
          textAnchor="middle"
          style={{ pointerEvents: 'none' }}
          fill="white"
        >
          {data.name}
        </Text>
        <Text
          className={styles.item__name}
          width={50}
          verticalAnchor="end"
          textAnchor="middle"
          style={{ pointerEvents: 'none' }}
          fill="white"
        >
          {data.type}
        </Text>
      </g>
```
I the reason I need 2 different text areas on top of each other is because they both have different font styles.

I could target `<tspan />` with css but I can't think of a reliable way to ensure what text lines appear on which `<tspan />` elements because it is abstracted.

**Comment by hshoff** [comment]
hi @dagda1, thanks for checking out vx!

Yes it is possible using the `dy` prop on to adjust the offset based on the bounding box height of the text above. example: https://codesandbox.io/s/y7659zz6x

Hope that helps!
