### ISSUE TITLE
Is it possible to add custom icons to the graph?

### ISSUE THREAD

**Issue by magdalko** [hshoff/vx#360]
Hi,

I am just wondering if this is possible to add to Area Graph icons in the specific point? Example below:

![skjermbilde 2018-09-21 kl 14 52 38](https://user-images.githubusercontent.com/31534726/45882310-163f3380-bdae-11e8-91e5-30987ff653eb.png)

I am new to the VX and I am not sure to what extent it is customizable 

Thanks for answer!

**Comment by hshoff** [comment]
Hi @magdalko, yes this is possible. Here's one approach: https://codesandbox.io/s/zwy39r2kll
<img width="554" alt="screen shot 2018-09-21 at 2 51 12 pm" src="https://user-images.githubusercontent.com/339208/45900468-e859ef00-bdad-11e8-8b17-fcbbf09e2f60.png">

Hope that helps and thanks for checking out vx!
