### ISSUE TITLE
Incorrect linting pattern in package.json

### ISSUE THREAD

**Issue by amilajack** [hshoff/vx#362]
The current eslint lint pattern (`eslint \"{packages,scripts}/**/*.js\"`) does not run on all the js files in the codebase. The correct pattern for eslint should be `eslint .`. Would a PR for this be welcome?

**Comment by williaster** [comment]
Thanks for raising this issue @amilajack.

The linting is relatively new, I'll play with it locally but PRs are always welcome 👍

**Comment by hshoff** [comment]
@amilajack which files is it missing? i get the same output for both patterns

**Comment by amilajack** [comment]
I linted all the js files with eslint by running the following command: `eslint . --fix`. Here's the results. https://github.com/amilajack/vx/commit/27c756aa92caedb69a1589be52be4dfd495964ed

**Comment by hshoff** [comment]
Right but it appears that the glob (`eslint \"{packages,scripts}/**/*.js\"`) works fine here. We only want to lint certain files. I have a PR coming that will update the rules/.eslintignore. Going to close this issue for now.
