### ISSUE TITLE
Using voronoi tessellation to select closest line in multiline charts

### ISSUE THREAD

**Issue by jens-ox** [hshoff/vx#364]
When making interactive multiline charts it is often necessary to provide some way to select a specific line. This can be nicely done using an invisible voronoi tessellation&mdash;when hovering the cell of a point, the line this point belongs to is marked active.

Example: [Multi-Line Voronoi](https://bl.ocks.org/mbostock/8033015).

Has anyone done this using vx? Or could this be integrated into vx?

![chrome_2018-09-28_13-42-32](https://user-images.githubusercontent.com/5368029/46206477-683f0680-c324-11e8-868c-52d5c121dfb2.png)

**Comment by hshoff** [comment]
Yes this is possible with vx. @williaster built this in a reusable chart form in [data-ui](https://github.com/williaster/data-ui). Example:
![screen shot 2018-09-28 at 10 30 52 am](https://user-images.githubusercontent.com/339208/46214678-b4308200-c309-11e8-8d1d-6461f4f3f51c.png)
https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=LineSeries&full=0&addons=0&stories=1&panelRight=0

vx provides the components to make it ([voronoi](https://vx-demo.now.sh/voronoi), [linePath](https://vx-demo.now.sh/lines)) but doesn't have the concept of a chart so it's not an out of the box thing at the moment.

**Comment by jens-ox** [comment]
That's great! I thought that `vx-voronoi` was only used as a visualization component and not as accessor.
