### ISSUE TITLE
@vx/responsive ParentSize position

### ISSUE THREAD

**Issue by loopmode** [hshoff/vx#366]
Hi
Just tried out the `ParentSize` component from `@vx/responsive`, it looked as if I could simplify my own code a lot with it.
However, there is one thing I don't understand: The top/left position values are always 0 for me.

I understand that ResizeObserver cares more about paddings and margins when providing that value, and since I have no margins/paddings, it remains 0. 
But I do have e.g. a variable-size sidebar sibling that pushes the svg area x, also an optional header toolbar that pushes the svg area y.
So, my use case is that I need the actual absolute coordinates on the screen, which, afaik, can only be retrieved using the rather expensive `getBoundingClientRect()` that will perform a full layout measuring. 
And that's what I do in my app, manually..

Would it make sense to implement such functionality into this package? 
Probably behind a flag that enables it, like `<ParentSize boundingRect>` or `<ParentSize absolute>` or similar.
And of course with some smart moves that minimize the calls to `getBoundingClientRect()`..

**Comment by williaster** [comment]
hey @loopmode, thanks for checking out `vx`! 

Can you be more specific about your example, or ideally link to a codesandbox to reproduce? Your description sounds like the [responsive demo in the gallery](https://vx-demo.now.sh/responsive), do you need more functionality than that? FWIW I'm not sure I've ever used `<ParentSize />` and had non-zero `top`/`left` values, but that hasn't been limiting for me. 

Depending on your exact needs, there's also the [`@vx/bounds` package](https://github.com/hshoff/vx/tree/master/packages/vx-bounds) which exports an `HOC` that gives the base component its bounding rect, as well as its parent's bounding rect. We've used this to implement responsive tooltips.

**Comment by loopmode** [comment]
Hi @williaster 
Well `@vx/bounds` looks just right, thanks for pointing it out.
Yet again it feels like I should have looked closer into `@vx` first, and  I would have saved myself some coding time.. :)
