### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by baisijian** [hshoff/vx#369]
import { letterFrequency } from '@vx/mock-data';
 cause: 
Cannot resolve 'file' or 'directory' ../../assets/x/mock-data

**Comment by hshoff** [comment]
hi @baisijian, could you provide some more information about your setup? what version of node? what OS? do you have a `node_modules/` directory that contains a `@vx/` directory? what version of `@vx/mock-data`?

**Comment by hshoff** [comment]
Well I'm not sure what's going on with your setup. Could try upgrading node, the latest version is `10.11.0`: https://nodejs.org/en/ only thing i can think of is maybe your `npm` client is < 2 and it's having trouble with scoped packages: https://docs.npmjs.com/misc/scope

I don't think this is a problem with `vx` though. Here's an example of it working without problem on codesandbox: https://codesandbox.io/s/y50kpx14j
