### ISSUE TITLE
guide issue

### ISSUE THREAD

**Issue by baisijian** [hshoff/vx#373]
hi @hshoff : 
I can not open the website https://medium.com/vx-code, I want to get some guide about component Tree from @vx/hierarchy, how to get it?

**Comment by hshoff** [comment]
Hi @baisijian, unfortunately we don't have a guide for @vx/hierarchy. We do have examples in they gallery here:

- https://vx-demo.now.sh/trees
- https://vx-demo.now.sh/dendrograms
- https://vx-demo.now.sh/pack
- https://vx-demo.now.sh/treemap

`d3-hierarchy` has great docs which should help as well: https://github.com/d3/d3-hierarchy#d3-hierarchy
