### ISSUE TITLE
how to import zoom behavior

### ISSUE THREAD

**Issue by baisijian** [hshoff/vx#374]
hi @hshoff ,  i am confuse about how to make the chart zoom in and out?

**Comment by hshoff** [comment]
@vx/zoom and @vx/brush aren’t done yet https://github.com/hshoff/vx/blob/master/packages/vx-zoom/src/Zoom.js. @vx/zoom progress is being tracked here: https://github.com/hshoff/vx/issues/7

There’s an example here of Zoom if you’re in need of the behavior now: https://codesandbox.io/embed/32j6874rx5
