### ISSUE TITLE
Responsive SVG Component Children Prop Only Accepts Function

### ISSUE THREAD

**Issue by NathanH81** [hshoff/vx#378]
The ResponsiveSVG component only accepts a function for the children prop, but I am able to add an array of JSX elements and it seems to work correctly and be responsive. Seeing the following error in console.

![vx-error](https://user-images.githubusercontent.com/7214789/47804587-2fb79180-dd03-11e8-98ac-1b3687db5b56.png)

```
ResponsiveSVG.propTypes = {
  children: PropTypes.func,
  width: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  height: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  xOrigin: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  yOrigin: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  preserveAspectRatio: PropTypes.string
};
```

**Comment by hshoff** [comment]
Looks like an incorrect prop type. Thanks for letting us know. We'll get it updated in an upcoming release.

Prop type checks are removed with production builds of react so feel free to continue passing an array of children and ignore the console warning. Another workaround would be to pass function for now that returns your array of children.

**Comment by hshoff** [comment]
oh! i should mention, you may want to check out `<ParentSize />` as an alternative to `<ResponsiveSVG />`: https://vx-demo.now.sh/responsive

**Comment by NathanH81** [comment]
Thanks for the information and fast response! Can't thank you enough for these packages. Really appreciate them. I will check out ParentSize as an alternative.
