### ISSUE TITLE
Is preact still compatible?

### ISSUE THREAD

**Issue by kono-paku** [hshoff/vx#397]
Hello,

I tried to use vx/vx with preact.
I do like to use both of them.
But, most examples is not working.

```
vx-shape.es.js?83e7:418 Uncaught TypeError: children is not a function
    at Component.AreaClosed [as constructor] (vx-shape.es.js?83e7:418)
    at Component.doRender [as render] (preact.js?10a9:229)
    at renderComponent (preact.js?10a9:271)
    at setComponentProps (preact.js?10a9:248)
    at buildComponentFromVNode (preact.js?10a9:339)
    at idiff (preact.js?10a9:134)
    at innerDiffNode (preact.js?10a9:176)
    at idiff (preact.js?10a9:152)
    at innerDiffNode (preact.js?10a9:176)
    at idiff (preact.js?10a9:152)
```

Only this one is working fine.
https://github.com/hshoff/vx/blob/master/packages/vx-demo/components/charts/SimpleBar.js

Do I have to do something for children attribute?

This page for supporting preact shows 404 error.
https://zeit.co/deployments/vx-preact.now.sh?redirect=1

I deeply appreciate for your time and efforts for such the great library.

**Comment by hshoff** [comment]
Need to use `preact-compat`. 

```
Children: Not necessary in Preact, because props.children is always an Array.
React.Children is fully supported in preact-compat.

**Comment by hshoff** [comment]
From the preact what's missing docs (https://preactjs.com/guide/differences-to-react#what-s-missing-):

>  - Children: Not necessary in Preact, because props.children is always an Array.
>    + `React.Children` is fully supported in [preact-compat](https://github.com/developit/preact-compat).

So looks like you need to add preact-compat and it should work.

**Comment by kono-paku** [comment]
I have added preact-compat, but it was not working.
Then, I changed preact framework into react one. 
It is perfectly fine.
It seems that preact-compat issue, though.
I will create issue on preact-compat github.
Thank you for checking out the inquiry.

**Comment by james-kraus-ck** [comment]
@hshoff, can we reopen this issue? I'm getting the same problem.

**Comment by james-kraus-ck** [comment]
Opened PR: https://github.com/hshoff/vx/pull/458
