### ISSUE TITLE
[gallery] call for community submissions

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#4]
**Making something cool with `vx`?**
Submit a pull request or post here and we'll get it added to https://vx-demo.now.sh/gallery

**Using `vx` in a project?**
Post the project/company name + link and we'll add it to the `Used By` list in the Readme.

**Comment by Fxlr8** [comment]
Where in the repo structure should gallery examples be placed?

**Comment by techniq** [comment]
@Fxlr8 - https://github.com/hshoff/vx/tree/master/packages/vx-demo

**Comment by hshoff** [comment]
At the moment I've been featuring community projects in the Readme's `In the wild`  section https://github.com/hshoff/vx#in-the-wild.

Plan is to add a vx-demo.now.sh/gallery/community page once we have more examples to feature.

**Comment by techniq** [comment]
I've been building up a catalog under my codesandbox - https://codesandbox.io/u/techniq/sandboxes that might be worth linking in as well at some point.

I just created a new tag on codesandbox [vx:example](https://codesandbox.io/search?query=&page=1&refinementList%5Btags%5D%5B0%5D=vx%3Aexample) to make it easier to search for other examples (useful to say also show me examples using `react-move`)
