### ISSUE TITLE
Question - How to control Link position and length

### ISSUE THREAD

**Issue by eilatc** [hshoff/vx#406]
Hi all,

I am using this example https://vx-demo.now.sh/trees to build some graph.

I am trying to customise the Horizontal Links but i can't find any docs that explain the options.

Basically this is what i want to achieve:

![picture11](https://user-images.githubusercontent.com/19334770/50842336-208e3900-136f-11e9-9553-5b9f661f440e.png)

**Current:**
The link starts from the beginning of the node till the beginning to the next node.

**Request:**
Link starts from the middle of the nodes and the length is controlled by a prop.

Thanks :)

**Comment by hshoff** [comment]
You would just need to center your Node's around the source/target point. This example centers the nodes this way: https://codesandbox.io/s/wy30kq4nqk
