### ISSUE TITLE
Multiple threshold graphs on the same page distort threshold fill

### ISSUE THREAD

**Issue by isaacgr** [hshoff/vx#410]
When adding multiple threshold graphs on the same page, the second graph (if using seperate data from the first) will have a distorted threshold fill. See attached image for issue. Code can be found here [https://github.com/isaacgr/TemperatureWebpage/blob/master/src/Graph.js](url).

I kind of think its related to the react component values I'm setting, but not sure how to address it. The bottom graph should have green above 30, and yellow below. If I make both graphs use the same data, or get rid of the top graph, then the threshold is not distorted.

![image](https://user-images.githubusercontent.com/20640588/51082010-df2dbe80-16cb-11e9-9493-18cc4a54f9ec.png)

**Comment by techniq** [comment]
If you add a unique 'id' prop to each graph, this should fix this

**Comment by techniq** [comment]
See https://github.com/hshoff/vx/issues/341
