### ISSUE TITLE
There are two packages having the boxplot implementation

### ISSUE THREAD

**Issue by dennisja** [hshoff/vx#412]
The boxplot implementation exists in two packages i.e [vx/boxplot](https://github.com/hshoff/vx/tree/master/packages/vx-boxplot) and [vx/stats](https://github.com/hshoff/vx/tree/master/packages/vx-stats). Why is it like this and What is the recommended package to use while implementing a box plot? Are both packages updated when someone contributes to the boxplot implementation?

**Comment by lucafalasco** [comment]
I also noticed this, here is the reason: https://github.com/hshoff/vx/blob/da07277d05501e6cad8f72b3cc88cefae174bc8b/CHANGELOG.md#v00147 

> #197 note: @vx/boxplot is deprecated in favor of @vx/stats in a future release @vx/boxplot will be removed

So I guess you should use `@vx/stats`

**Comment by dennisja** [comment]
Thanks @lucafalasco
