### ISSUE TITLE
BarStack children

### ISSUE THREAD

**Issue by aishmitk** [hshoff/vx#413]
I am having a difficult time working with the children of `<BarStack />`. I know that to have an interactive graph I need to define the children myself.

Looking at the example, the function in which children are created contains has an argument called `barStacks`. There is no declaration for this variable anywhere, so I am confused as to what to make the values of these values.

`fill` and `key` are fairly straightforward, and assuming that the `height` is just the value of the bar, that should be okay too. For `<BarGroup />`

But what am I supposed to make `x` and `y`? It is extremely unintuitive to just know where each bar should go according to its values. Is there any documentation for this children prop?

**Comment by hshoff** [comment]
Here's an interactive example with `<BarStackHorizontal />`: https://vx-demo.now.sh/barstackhorizontal

The function you pass to `<BarStack />` as children will be called with an array as it's first argument. You can name the first argument whatever you want, i chose to call it `barStacks` in the demo. Until better docs come around, you can see the source here: https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/BarStack.js#L72 

typical usage would be:

```js
<BarStack>
  {barStacks => {
    return barStacks.map(barStack => {
      return barStack.bars.map(bar => {
        return (
          <rect
            key={`${barStack.index}-${bar.index}`}
            x={bar.x}
            y={bar.y}
            width={bar.width}
            height={bar.height}
            fill={bar.color}
            onClick={event => {
              alert(`clicked: ${JSON.stringify(bar)}`);
            }}
          />
        );
      });
    });
  }}
</BarStack>
```

Hope that helps!

**Comment by aishmitk** [comment]
Hey that helps a lot, in the source it shows that there is a `barHeight = yScale(y0(bar)) - yScale(y1(bar))`. I have the `x` props set, but I cannot seem to get the `y` props done (`y` and `height`). What exactly is `bar` and how does it differ from `bar.data`?

**Comment by hshoff** [comment]
I recommend having a look at `stack` from `d3-shape` for more info: https://github.com/d3/d3-shape/blob/master/README.md#stacks
