### ISSUE TITLE
Tree is not generated - nodes stacked one on another

### ISSUE THREAD

**Issue by vkallore** [hshoff/vx#416]
I've copied the script from https://vx-demo.now.sh/trees and all nodes stacked over previous node. Tried on Chrome & Firefox. Using latest `vx 0.0.183` and `React V16.7.0`

[Code Sandbox Example](https://codesandbox.io/s/3vxw62xqn6)

Can somebody help me to get it working? :)

**Comment by scraperg** [comment]
Hi,

I think you just need to give App height and width props. They're defaulting to undefined.

**Comment by hshoff** [comment]
scraperg is correct. Need to provide width and height props. Here's a working example: https://codesandbox.io/s/ywyxo8lqkv
