### ISSUE TITLE
Multiple Parents - Generate line from mid of another

### ISSUE THREAD

**Issue by vkallore** [hshoff/vx#417]
This is not an issue, might be a feature request/discussion.

Currently, I'm trying to have a family tree which will have

1. Spouses/Partners (Multiple)
1. Children of Spouses/Partners

As per D3 tree structure, we could have only one parent for a child, so in order to generate a tree as per my choice, I had to align partners as children of a member. And with additional JSON key, I style the partners. See the example below.

![Family Tree with Partners as Children](https://user-images.githubusercontent.com/5166249/51740542-585ce680-20ba-11e9-9311-0e53d2cea104.png)

The same is available in [my repo](https://github.com/vkallore/d3-vx-family-tree/tree/lab/spouse)

I am impressed the way how _Cyril Cherian_ tried to implement the tree with partners in [this JSFiddle](http://jsfiddle.net/cyril123/fcd5q8fv/1/), and I made a [fork of it](http://jsfiddle.net/Vaishak/x6bg9dcu/) and made some changes.

![Family Tree wiht Partners](https://user-images.githubusercontent.com/5166249/51740567-66126c00-20ba-11e9-9d23-2fabed2b03d2.png)

But the problem with this is that it cannot have multiple spouses/partners in a clean/straighforward way, will have to modify the JSON very badly.

Same JSFiddle script is also avalable in [my repo](https://github.com/vkallore/d3-vx-family-tree/blob/lab/spouse/src/d3-single-spouse.html)

**I would like to have the mix of both, where**

1. Partners will be aligned with member of the tree
1. Partner will not have the line from any other node (unless mentioned)
1. Children will be originating from the mid of Partners line

**Comment by vkallore** [comment]
Hey, I couldn't generate the children from mid of partner line, however done something to achieve 80% of how I wanted. 

See the PR - https://github.com/vkallore/d3-vx-family-tree/pull/1

**Comment by hshoff** [comment]
Nice, happy you were able to support your use case.

This is a pretty specific implementation and vx hasn't yet ventured into custom hierarchical layouts, so at this time, vx won't have a family tree layout.

It might be worth making a tutorial to share with others on how to make a family tree with vx like your example above. I bet there's are folks that would be grateful that you shared your efforts.

As this isn't a bug with vx, I'm going to close this for now. Happy to reopen if there is further discussion.

**Comment by vkallore** [comment]
I have the implementation of first screenshot [here](https://github.com/vkallore/d3-vx-family-tree); not sure on the code quality, but it works :)

Demo can be viewed on [now.sh](https://vk-ft.now.sh) 

Note: Demo site might not load quick as it might go idle. Currently the demo/code base has static JSON. I might update the codebase here or in another implementation of it. But I am sure its pretty easy to get data from server with ease.

**Comment by hshoff** [comment]
Added a link to your demo here: https://github.com/hshoff/vx/commit/8f399add48a51114c6385dc10e22d45aa2b2b26f

**Comment by designbyadrian** [comment]
> Added a link to your demo here: [8f399ad](https://github.com/airbnb/visx/commit/8f399add48a51114c6385dc10e22d45aa2b2b26f)

The link is now dead 😔
