### ISSUE TITLE
Animation example and xScale for AreaClosed

### ISSUE THREAD

**Issue by EugeneDraitsev** [hshoff/vx#421]
Hi, I tried to use [this](https://codesandbox.io/embed/j3x61vjz5v) animation example and seems like it works supernice, but if I will try to update `@vx/shape` from 0.0.153 -> 0.0.184 it stop works because in 0.0.184 `<AreaClosed />` don't have xScale prop (but still have yScale). I tried to search explanation of it in this repo and google it, but I didn't find anything about that. So, can you explain what the reason of removal `xScale` prop and how I can rewrite this code to use it without `xScale`:

```jsx
const Graph = ({ interpolate, data, xScale, yScale }) => (
  <AreaClosed
    data={data.map((d, i) => ({ ...d, value: interpolate[i] }))}
    xScale={xScale}
    yScale={yScale}
    x={x}
    y={y}
    strokeWidth={2}
    stroke={'url(#PinkRed)'}
    fill={'url(#PinkRed)'}
    curve={curveBasis}
  />
)
```

**Comment by EugeneDraitsev** [comment]
Seems like I solved it. If someone will face with similar problem, then [here](https://codesandbox.io/s/vjjz035417) you can find updated version of animation example and solution is: 

```jsx
const Graph = ({ interpolate, data, xScale, yScale }) => (
  <AreaClosed
    data={data.map((d, i) => ({ ...d, value: interpolate[i] }))}
    yScale={yScale}
    x={d => xScale(x(d))}
    y={d => yScale(y(d))}
    strokeWidth={2}
    stroke={'url(#PinkRed)'}
    fill={'url(#PinkRed)'}
    curve={curveBasis}
  />
)
```

**Comment by hshoff** [comment]
explanation is here: https://github.com/hshoff/vx/pull/383
