### ISSUE TITLE
Pack returns NaN for r, cy, cx

### ISSUE THREAD

**Issue by sdgandhi** [hshoff/vx#430]
Copied the pack example here: https://vx-demo.now.sh/pack

to codesandbox: https://codesandbox.io/s/0y4zyq465p

See console.

**Comment by hshoff** [comment]
Hi @sdgandhi, thanks for checking out vx!

The `width` and `height` props are undefined in your codesandbox. Here's a working example with width and height props set: https://codesandbox.io/s/j30p0kj8w?fontsize=14

**Comment by sdgandhi** [comment]
Ah @hshoff, thanks
