### ISSUE TITLE
Code Sandbox(or something similar) for all examples in gallery.

### ISSUE THREAD

**Issue by vaibhavhrt** [hshoff/vx#432]
Providing a code sandbox for all examples in gallery will make it easier for users to make some changes to the examples and run it to see the results. Right now user has to set up a project, install dependencies then copy paste the example code to try it out themself.

**Comment by hshoff** [comment]
True. I'll see what I can do about this.

**Comment by vaibhavhrt** [comment]
I can help set up code sandbox if you can tell me where to put what.

**Comment by williaster** [comment]
great idea! ❤️

**Comment by PascalSenn** [comment]
The CLI of CodeSanbox is pretty great. You can probably update the sanboxes easily in the CI/DI pipeline

**Comment by curran** [comment]
I'd be interested in getting some of the examples to work in VizHub, a platform I'm working on.

The blocker at the moment is that I see there is no monolithic build that contains all `@vx/*` modules. This is problematic if you're working with `<script>` tags for getting dependencies into the page (which I do realize is a bit outmoded, but sometimes still desirable). As it stands, there are browser builds for each module, and one needs to fiddle with the ordering in case there are any dependencies.

Would there be interest in publishing such a package? Perhaps as `@vx/vx` or `@vx/all`?

FWIW I just got an example of Semiotic working, this is what it looks like: https://beta.vizhub.com/curran/18764c3c843748709584094fce2a904a?edit=files&file=index.js

**Comment by williaster** [comment]
Hi @curran 👋 , thanks for checking out `vx`.

Excited you're thinking of adding some `vx` examples to `VizHub`! Have you seen or tried the [`@vx/vx` package](https://www.npmjs.com/package/@vx/vx)? It [exports everything from every package](https://github.com/hshoff/vx/blob/master/packages/vx-vx/src/index.js).

**Comment by williaster** [comment]
noting that the sandbox updates are well underway in #624. I'm going to close this and track there.
