### ISSUE TITLE
[BUG/ENHANCEMENT] Cannot use custom projection with vx/geo

### ISSUE THREAD

**Issue by SuperMayo** [hshoff/vx#433]
The [docs](https://vx-demo.now.sh/static/docs/vx-geo.html) list the __Projection__ component but it cannot be used to create a custom projection. If one tries to import Projection:
`import { Projection } from "@vx/geo`
it will lead to the following error:
`Attempted import error: 'Projection' is not exported from '@vx/geo'`

Would it be possible to make it accessible?

Last question: is there a workaround to pass a custom d3 projection into vx ?

**Comment by hshoff** [comment]
Yeah no problem: https://github.com/hshoff/vx/pull/434 will land in the upcoming `@vx/geo v0.0.187`
