### ISSUE TITLE
web application with many entity and large data with grid

### ISSUE THREAD

**Issue by mammadkoma** [hshoff/vx#438]
Hi all and pardon me because i'm a beginner in node js framework.
imagine we have a system with 100 entity for data entry.
Is there a sample or step by step video or article for easiest solutions and with lowest coding for making this project with these features :
1- create model(poco) layer and just write entity properties and its validation attribute for backend and frontend validations.
2- create a form automatic with a grid with these features :
a) paging & sorting & filtering for each column header.
b) data entry (insert and delete and update) for master entity.
c) open each row by plus sign click for show details entities.
d) add some custom buttons in rows for execute an action or api on server and database.
2- project can work with sqlite database or sqlserver.
3- project can give access or deny some web page and insert & delete & update &custom buttons. 
and I just write a query for create a ViewModel for grids.

**Comment by hshoff** [comment]
Hi @mammadka, thanks for checking out vx. Your question is out of scope of this repo, I recommend posting your question to https://stackoverflow.com/
