### ISSUE TITLE
Add easy to use chart point tooltip 

### ISSUE THREAD

**Issue by hbourzeix** [hshoff/vx#44]

**Comment by hshoff** [comment]
Yup! This is coming.

**Comment by jacek213** [comment]
any progress on this one?

**Comment by Flaque** [comment]
🎉🎉🎉

**Comment by williaster** [comment]
psyched to see this! 🎉 🏆

**Comment by k3rmitt** [comment]
So 1337!

**Comment by thienanle** [comment]
@hshoff does this work with `LinePath`/`AreaClosed`?

**Comment by hshoff** [comment]
@thienanle it does but it's a bit more involved. I'm working on making this easier for folks, but haven't settled on an api I'm happy with just yet.

Here's an example of how it works: https://www.webpackbin.com/bins/-KpGjCM5yQ4nkND4c-P-

![area-tooltip-demo](https://user-images.githubusercontent.com/339208/28283302-3b3c58f4-6ae2-11e7-9cf2-215faf4a4611.gif)

Things to note:

1. use a stateful react component (`class`) so you can using `ref` on the `<svg ref={s => this.svg = s}>`, you'll use this in your event handlers
1. i'm using a transparent `<Bar />` overlay on top of the chart to handle the mouse events
1. `onMouseMove`

  ```js
  // convert event coords to local svg coords
  const { x } = getCoordsFromEvent(this.svg, event);
  // use xScale.invert to get x value
  const x0 = xScale.invert(x);
  // use d3-array bisector to find the data value
  const index = bisectDate(data, x0, 1);
  const d0 = data[index - 1];
  const d1 = data[index];
  const d = x0 - xStock(d0.date) > xStock(d1.date) - x0 ? d1 : d0;

  // use `withTooltip`s `showTooltip()` to update the position and data
  showTooltip({
    tooltipData: d,
    tooltipLeft: x,
    tooltipTop: yScale(d.close),
  });
  ```

I'm hoping to make this easier in the future as I'll be needing to use it for @vx/brush @vx/drag interactions . But for now this should get you up and going with position based on event positions.

Happy to answer any questions if things come up.

**Comment by thienanle** [comment]
@hshoff thank you for the example, super helpful!

Yes it would be great to not have to use a transparent `<Bar />` and have the mouse events on the `<AreaClosed />` instead. Thanks for your work on this!

I was also thinking, in the case where a chart has more than 1 series (multiple `<LinePath />` components for example), would it make sense to put the mouse events on each? Perhaps on a wrapping component (something like `<Group />`) would make more sense?

**Comment by hshoff** [comment]
@thienanle yup! you can put the events on the `<AreaClosed />` as of `@vx/shape@0.0.131`

Example: https://www.webpackbin.com/bins/-KpN6KNn40htehDwd80C
![path-events](https://user-images.githubusercontent.com/339208/28344763-94833a1a-6bda-11e7-9205-eeb156842015.gif)

For multiple `<LinePath />`s it depends what you're trying to do, you could put them on each or you could put it on a `<Group />` like so: https://www.webpackbin.com/bins/-KpN9sBHl_pBgbCcLFCt

**Comment by thienanle** [comment]
@hshoff have you tested this on `<Arc />`? I love the feature of getting the hovered arc section data `onMouseMove`, but I'm getting an error

```
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
```

**Comment by hshoff** [comment]
@thienanle could you post your `onMouseMove` function? happy to take a look.

**Comment by thienanle** [comment]
```
onMouseMove={data => event => {
	const { x, y } = localPoint(this._svg, event);

	showTooltip({
		tooltipData: data,
		tooltipLeft: x,
		tooltipTop: y,
	});
}}
```

Calling `showTooltip` is what seems to cause the warning.

**Comment by thienanle** [comment]
I solved my issue by calling `showTooltip` on `onMouseMove` on `<Group />` and setting `tooltipData` to my component's state (so that I can get the data for the hovered pie).

```
<Group
	onMouseLeave={hideTooltip}
	onMouseMove={event => {
		const { x, y } = localPoint(this._svg, event);

		showTooltip({
			tooltipLeft: x,
			tooltipTop: y,
		});
	}}
>
	<Arc
		onMouseMove={data => event => {
			this.setState({
				tooltipData: data,
			});
		}}
	/>
</Group>
```

But it would be nice to not have to do this!

**Comment by joshnabbott** [comment]
@hshoff any way you could update the links to those examples? They no longer seem to work: https://www.webpackbin.com/bins/-KpGjCM5yQ4nkND4c-P-

**Comment by ilyhryh** [comment]
@hshoff second

**Comment by rachelombok** [comment]
@hshoff third

**Comment by williaster** [comment]
The demos all now link out to code sandboxes, [this is the `Areas` sandbox](https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-area).

As harry said above, there is an invisible `Bar` on top of the Areas which triggers the tooltip anywhere you mouse over, but you could change this behavior by moving the `onMouse/TouchMove` handler to the `Area`, or whatever is relevant for your series shape.

**Comment by olegKusov** [comment]
Please show example with normal tooltip for multiline chart (hover on marker circle should show value of series item).
