### ISSUE TITLE
@vx/legend: LegendLabel not customizable with className or style props

### ISSUE THREAD

**Issue by djizco** [hshoff/vx#444]
LegendLabel doesn't receive a className or style prop meaning you can't add custom styles such as font size or color.  I believe LegendItem has the same issue.

**Comment by xrpza** [comment]
I know this is an old thread, but I'm responding here in case others need the info.

You can achieve the styling you're looking for by specifying formatting the Child of `LegendLabel`. For example, you could employ `<span>` as follows to color the label:

```
 <LegendItem 
    key={`legend-key-here`} 
    margin={"0 5px"}
 >
    <svg width={15} height={15}>
        <rect fill={"#51bcda"} width={15} height={15} />
    </svg>
    <LegendLabel
        align={"left"}
        margin={"0 0 0 4px"}
    >
        <span className={"#51bcda"}>My Label</span>
    </LegendLabel>
</LegendItem>
```
