### ISSUE TITLE
Bar stack horizontal is breaking, saying that zScale is marked as required in 'BarStackHorizontal but its value is undefined'. 

### ISSUE THREAD

**Issue by okanji** [hshoff/vx#448]
![image](https://user-images.githubusercontent.com/30703259/55983482-1a4e7800-5c50-11e9-9e63-f61774d98254.png)

**Comment by hshoff** [comment]
@okanji the zScale prop is a function that returns the color for each segment in the bar stack based on the key. Here's an example of it working on the latest version of `@vx/shape`: https://vx-demo.now.sh/barstackhorizontal using an ordinal scale to map keys to colors.

But you could also do `zScale={key => 'blue'}` if you wanted each segment to be blue. 

here's the source: https://github.com/hshoff/vx/blob/8b3a6fe0c6997caef243009ea47121313f520672/packages/vx-shape/src/shapes/BarStackHorizontal.js#L65

note: looks like you're on an older version of @vx/shape as the `zScale` prop was renamed `color` about 6 months ago.

**Comment by okanji** [comment]
Thank you for your reply, this sorted me out and it works now. Much appreciated.
