### ISSUE TITLE
How to you vx in React Native

### ISSUE THREAD

**Issue by Achilles718611** [hshoff/vx#449]
Is it possible to use vx in React Native?

**Comment by hshoff** [comment]
Hi @Achilles718611, this is not currently possible. But there's a fork that has made progress towards making it work: https://github.com/hshoff/vx/issues/246

**Comment by shub113** [comment]
Hi, any update on this??

**Comment by Achilles718611** [comment]
Thanks for your reply.
I used another alternative library called "react-native-svg-charts".
https://www.npmjs.com/package/react-native-svg-charts
It's similar with VX.
