### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by j1mie** [hshoff/vx#455]
The latest version of Chrome throws the following error with the [Zoom component](https://vx-demo.now.sh/zoom-i):

```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
```

**Comment by hshoff** [comment]
Ah yes, this is a fun one. Will get this fixed in a non-breaking way (hopefully).

related
- https://developers.google.com/web/updates/2019/02/scrolling-intervention
- https://github.com/facebook/react/issues/14856
- https://github.com/facebook/react/issues/6436

**Comment by j1mie** [comment]
Thanks for your quick response @hshoff!

Wondering if you have any thoughts on how to implement pinch-to-zoom using a trackpad for the zoom component. I could post this in a separate issue if it's unrelated.
