### ISSUE TITLE
Drag to select range

### ISSUE THREAD

**Issue by andreyvital** [hshoff/vx#457]
Hey, is there any way to display a tooltip based off a range selected? I want to do something like this:

![Kapture 2019-05-06 at 13 35 55](https://user-images.githubusercontent.com/967317/57241732-09531580-7008-11e9-904c-7e915b6c84b2.gif)

**Comment by hshoff** [comment]
Hi @andreyvital, thanks for checking out vx. You would be looking for a brush component, which is still a work in progress. Progress is being tracked here: https://github.com/hshoff/vx/issues/14

Until it lands, you can check out https://github.com/williaster/data-ui/tree/master/packages/xy-chart/src/utils/brush as a reference implementation.

**Comment by andreyvital** [comment]
Thanks @hshoff—do you have any ETA for an official Brush impl?

**Comment by hshoff** [comment]
> do you have any ETA for an official Brush impl?

I do not

**Comment by andreyvital** [comment]
@hshoff is it possible now to do that type of selection?

**Comment by guillotegg** [comment]
is this already possible?

**Comment by aiaruu** [comment]
https://airbnb.io/visx/docs/brush
https://codesandbox.io/p/sandbox/visx-demo-brush-6nmosj?file=%2FExample.tsx%3A121%2C5
