### ISSUE TITLE
Road to V1?

### ISSUE THREAD

**Issue by ericchen0121** [hshoff/vx#459]
Considering using this for an app. It still looks like it's somewhat being maintained/used, but the Projects tab has a surprising lack of activity in the past year and a half (Looks like some documentation work was done earlier this year)

Just wanted to make sure this is still being worked on before committing to testing it out.

**Comment by hshoff** [comment]
Hi @ericchen0121, thanks for checking out vx. Yes, this is still actively being worked on. The last big piece is the Brush.
