### ISSUE TITLE
Arc component is broken with zero values

### ISSUE THREAD

**Issue by dmitriirudakov** [hshoff/vx#462]
`<Arc />` component does not work correctly with parameters equal to zero. 
In my case the component is completely broken when pass `startAngle` or `endAngle` equals to zero.
File: https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/Arc.js

<img width="785" alt="Vx" src="https://user-images.githubusercontent.com/17123205/57756035-7438d680-7703-11e9-9f96-2a57ac02aec3.png">

I believe in reality you want to check for null and undefined values.

**Comment by hshoff** [comment]
ah yes, thanks for the bug report!
