### ISSUE TITLE
AreaStack bad scale

### ISSUE THREAD

**Issue by MartinClement** [hshoff/vx#463]
Hey !

First thanks for your work and your beautiful components !

I want to use the AreaStack component in my Charts graph but I'm encountering an issue with the render of the component. Each last Area is not rendered correctly. No matters of the number of Area or range/domain props, the last one is alway bigger than she should.

```
import { Group } from '@vx/group'
import { AreaStack } from '@vx/shape'
import { AxisLeft, AxisBottom } from '@vx/axis'
import { scaleTime, scaleLinear, scaleOrdinal } from '@vx/scale'

let data = [
  { date: '2012-04-23T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 0 },
  { date: '2012-04-24T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 80 },
  { date: '2012-04-25T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 0 },
  { date: '2012-04-26T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 80 },
]

const keys = ['Group1', 'Group2', 'Group3', 'Group4']
const x = d => new Date(d.date)

const xScale = scaleTime({
  domain: [x(data[0]), x(data[3])],
})
const yScale = scaleLinear({
  domain: [0, 248],
})
const zScale = scaleOrdinal({
  range: ['#ff0000', '#00ff00', '#0000ff'],
  domain: keys,
})

const Test = ({ width, height, margin }) => {
  const xMax = width - margin.left - margin.right
  const yMax = height - margin.top - margin.bottom

  xScale.range([0, xMax])
  yScale.range([yMax, 0])

  return (
    <svg width={width} height={height}>
      <Group top={margin.top} left={margin.left}>
        <AreaStack
          keys={keys}
          data={data}
          stroke="none"
          strokeWidth={2}
          x={d => xScale(x(d.data))}
          y0={d => yScale(d[0])}
          y1={d => yScale(d[0] + d[1])}
          fill={d => {
            console.log(d)
            return zScale(keys[d.index])
          }}
        />
        {/* <AxisLeft scale={yScale} />
        <AxisBottom top={yMax} scale={xScale} /> */}
      </Group>
    </svg>
  )
}

export default Test
```
There is a simple exemple to illustrate my case. Group1 and Group2 are correctly displayed but Group3 is not. You can see in data that Group3 ( blue ) should alternate between 0 and 80. But it's not the case : Blue never equal 0.

![Capture d’écran 2019-05-16 à 14 41 02](https://user-images.githubusercontent.com/29033932/57854585-e0d9d100-77e8-11e9-8677-4ce0ce6c2d02.png)
 
And as I said, if I add a 4th Group, Group3 is correctly rendered but Group4 is not.
 ```  
...
let data = [ // Add Group4
  { date: '2012-04-23T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 0, Group4: 10 },
  { date: '2012-04-24T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 50, Group4: 10 },
  { date: '2012-04-25T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 0, Group4: 10 },
  { date: '2012-04-26T04:00:00.000Z', Group1: 60, Group2: 30, Group3: 80, Group4: 10 },
]
...
const zScale = scaleOrdinal({
  range: ['#ff0000', '#00ff00', '#0000ff', '#000'], // add color for Group4
  domain: keys,
})
```
![Capture d’écran 2019-05-16 à 14 46 56](https://user-images.githubusercontent.com/29033932/57854846-7d9c6e80-77e9-11e9-9761-9fb16771daab.png)

Blue ( Group3 ) is correctly displayed, but Black does not correspond to Group4 ( value to big ).

I tried to tweak domaine on yScale, didn't fixed that. I assume that the problème comes from the scaling but and can't find a way to fix it..

Hope you guys could help me with it =)

Have a nice day !

**Comment by hshoff** [comment]
Hi @MartinClement, thanks for checking out vx!

Here's a working example: https://codesandbox.io/embed/upbeat-goldwasser-gywd1

Here's the fix:

```diff
-  y1={d => yScale(d[0] + d[1])}
+  y1={d => yScale(d[1])}
```

**Comment by MartinClement** [comment]
Thanks a lot ! I missed this one ...
