### ISSUE TITLE
Use PhantomJS to generate charts in automated reports or emails

### ISSUE THREAD

**Issue by bindai** [hshoff/vx#465]
Is there a way to generate charts in automated reports or emails? 

So we can have consistent images between the front and back end.

The [link](https://www.highcharts.com/docs/export-module/render-charts-serverside) shows how highcharts do.

**Comment by hshoff** [comment]
Hi @bindai thanks for checking out vx!

Looks like highcharts provides a server that outputs charts in various formats. This is currently outside the scope of vx. 

You might be able to use Google's Puppeteer https://pptr.dev/ to generate screenshots programatically. 

Another option might be one of the various svg-to-png solutions out there like the NY Time's Crowbar:  https://github.com/nytimes/svg-crowbar

Report back if you figure this out and get it working, this would be a great addition to the vx docs as a how-to guide!
