### ISSUE TITLE
[vx-demo] Add webkit overflow touch to demo website

### ISSUE THREAD

**Issue by hanford** [hshoff/vx#47]
On iOS, scrolling the demo website locks everytime the thumb is released, unfortunately this is default behavior on iOS unless you add `-webkit-overflow-scrolling: touch;` to the scrollable element. This will add inertia like scrolling.

**Comment by hshoff** [comment]
This has been bugging me as well. Will get this fixed today.

**Comment by hshoff** [comment]
fix is live https://vx-demo.now.sh/gallery
