### ISSUE TITLE
Horizontal boxplot displays incorrectly

### ISSUE THREAD

**Issue by LambStack** [hshoff/vx#471]
<img width="510" alt="Screen Shot 2019-07-01 at 3 41 26 PM" src="https://user-images.githubusercontent.com/24273374/60470800-b7e59200-9c16-11e9-8f96-f133a105af96.png">

When you set horizontal=true to a @vx/boxplot they rectangle is placed in the wrong spot.
This can be fixed, though, by moving the line
`boxplot.box.y1 = valueScale(firstQuartile);` 
to before the previous line in BoxPlot.js.

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/472
