### ISSUE TITLE
Zero of y-axis  in the wrong position

### ISSUE THREAD

**Issue by bindai** [hshoff/vx#473]
The zero of y-axis is in the wrong position when there is only one piece of data like this [{k: 1553356800000, v: 0}]. 

You can see demos from the screenshots below. 

![image](https://user-images.githubusercontent.com/5703598/60581608-c324f300-9db9-11e9-8250-a2ac5fd20d72.png)

![image](https://user-images.githubusercontent.com/5703598/60581747-05e6cb00-9dba-11e9-806f-189d6a71dbea.png)

**Comment by hshoff** [comment]
This has to do with a change `d3-scale` made in `2.2.2`: https://github.com/d3/d3-scale/issues/117

This means in the situation where all values are `0` you’ll want to update the scale domain to `[0,1]`.

Hope this helps!
