### ISSUE TITLE
withBoundingRects for vx/Group?

### ISSUE THREAD

**Issue by lapidus** [hshoff/vx#481]
Thanks for a great lib!

I'm rendering a legend (Group) with different sized labels and would like the ChartCanvas to use the remaining width (when the Legend width is known). Would `withBoundingRects` work for this case or would I better throw each component inside a `div` to get the benefits of HTML layouting? Thanks for any hints!

```

<ChartContainer>

  <ChartCanvas width={parentWidth - legendWidth} /> //should be recalculated when Legend size is known

  <Group id="Legend">
    <Text>My label</Text>
    <Text>A super long label</Text>
  </Group>

</Chart>
```

**Comment by hshoff** [comment]
If it's not too much extra work, I'd recommend going with div's and html/css for layout a case like this. You'll have more control and freedom with less bookkeeping. 

That said let's explore some options:

1. fix legend width based on percentage of parent container width
```jsx
<ParentSize>
  {parent => {
    const legendWidth = x% * parent.width;
    const chartWidth = parent.width - legendWidth;
    // ...
  }}
</ParentSize>
```
2. callback to container when legend width known. this way the child legend can talk to the parent and update chart width once it is known
```jsx
// Legend.jsx
componentDidMount() {
  const { onLegendBounds } = this.props;
  const bounds = this.ref.getBoundingRects();
  onLegendBounds(bounds);
  // may want to do this again if legend props change
  // so could put this in a diff lifecycle method or
  // onMount create a ResizeObserver and call `onLegendBounds` when changes happen
}

// Container.jsx
onLegendBounds(bounds) {
  this.setState({ legendBounds: bounds })
}

render() {
  const { legendBounds } = this.state;
  return (
     <ParentSize>
      {parent => {
        const chartWidth = parent.width - legendWidth; // based on legendBounds
        // ...
      }}
    </ParentSize>
   );
}
```

3. let browser handle layout and have chart width be responsive to container. The best example is probably https://vx-demo.now.sh/responsive where the chart's width responds to the width of it's parent container which is determined by the browser and css

hope this helps!

**Comment by lapidus** [comment]
Super helpful, very appreciated! Thank you!
