### ISSUE TITLE
[heatmaps] Should heatmaps use an accessor?

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#51]
Right now `heatmaps` require the user to pass in data that looks like:
``` javascript
const data.bins = [ { bin: 0, count: 54.3050232 }, ...]
``` 

Why not have bin accessors? 

``` javascript
const bins = d => d.myBins
const bin = b => b.myBin
const count = b => b.myCount
```

**Comment by hshoff** [comment]
Ah yes, forgot to finish that. Thanks for catching that. Fixed it here: https://github.com/hshoff/vx/pull/49/commits/30cea681b6a59847c48ae2f8b50644bd70f42cb4. Will go out in `v0.0.116`.
