### ISSUE TITLE
how i can  install 'vx'?

### ISSUE THREAD

**Issue by jockw** [hshoff/vx#54]
when i install vx use 'npm install vx ' ,i am find that  the 'vx' i had installed didn't your 'vx',so how can i install your 'vx'

**Comment by williaster** [comment]
Vx is broken down into multiple packages (`@vx/axis`, `@vx/shape`, etc.) with the idea that you install what you need and can minimize bundle size. 

Also note that because these are all name-spaced packages you need a `@` before vx. so something like `npm install @vx/axis` should work.

**Comment by hshoff** [comment]
Hi @jockw thanks for checking out vx. As @williaster said, vx is a library of packages so you only need to install what you need. 

I'll give this some thought. Going to close this in favor of https://github.com/hshoff/vx/issues/33

**Comment by jockw** [comment]
thankyou

**Comment by hshoff** [comment]
To lower the friction to get started with vx, there is now `@vx/vx`

```bash
npm install --save @vx/vx react react-dom
```

```js
import { scaleLinear, AreaClosed, withTooltip } from '@vx/vx';
console.log(scaleBand);
console.log(AreaClosed);
console.log(withTooltip);

// or put everything under a vx namespace
import * as vx from '@vx/vx';
console.log(vx.scaleBand);
console.log(vx.AreaClosed);
console.log(vx.withTooltip);
```
