### ISSUE TITLE
Typescript compiles error

### ISSUE THREAD

**Issue by geekplux** [hshoff/vx#542]
The following error showed in local demo pages, when I launch vx-demo to develop.

```sh
Failed to compile
C:/project/vx/packages/vx-shape/esm/shapes/BarStack.js
Attempted import error: 'NumAccessor' is not exported from './Stack'.
```

There seems is a compile error of TypeScript, **`type` variables** wrote by ts **are not exported successfully** in ESM format.

PS: I've `npm run build` in root path and run `lerna bootstrap`, then `npm run dev` in vx-demo.

**Comment by geekplux** [comment]
@williaster so our master branch is stable? or some steps I also need to do before run demo?

**Comment by geekplux** [comment]
`WithBoundingRectsProps` is not exported in vx-bounds, too.

**Comment by williaster** [comment]
@geekplux thanks for checking out `vx` and opening the issue. The TypeScript is pretty fresh so apologies if there are some kinks to work out.

Types are _only_ generated for  the `lib/` build and not the `esm/` build (and this is specified in the [`package.json` of each TS package](https://github.com/hshoff/vx/blob/master/packages/vx-shape/package.json#L8) so I'm surprised there are errors). AFAIK the demo should be stable on `master` but I'll verify this now.

Apologies that are [docs are now stale for local development](https://github.com/hshoff/vx#development), I'll fix this asap. Basically we have switched to `yarn` and `yarn` workspaces to simplify / re-use config for the monorepo, and so the steps should now be

0) clone the repo
1) install `yarn` (globally or in the monorepo root)
2) run `yarn` in the monorepo root to install all dependencies and symlink packages (this replaces `lerna bootstrap`)
3) run `yarn build` to generate `.js` + types

After this you should be able to run `yarn run dev` in `packages/vx-demo`. Let me know if this fixes things or if you still encounter issues while I try to repro.

**Comment by williaster** [comment]
on a fresh build from `master` I *do* see this error.

**Comment by geekplux** [comment]
Thanks for your reply.
Seems `yarn workspace` is a trend now, it is being used in my side project, good development experience. But I don't know if it can replace lerna totally.

That sounds great if this issue is just docs tweaks. (This afternoon, I run vx-demo without errors by commenting out some code of example components. LOL)

I was going to complete Brush component, and I noticed it exists in your data-ui library, so could you please migrate it to vx? or let me help, I can develop it in typescript and make a demo put into vx-demo.

BTW:
I see the process of rewriting of typescript, any help I can provide?
Besides, the issues of Brush and Sankey layout have existed for a long time, I plan to make some contributions to them recently, don't hesitate to tell me if there anything I need to be informed.

**Comment by williaster** [comment]
👍 great re your workaround, I hope to have a fix out today. 

if you are interested in porting the `data-ui` `Brush` to `vx` that would be great! 🎈it's been on our backlog for a while and we just haven't gotten to it. Similarly, if you're interested in helping with the `TypeScript` re-write, we're happy to have more help. The remaining packages are a bit trickier than others though (scales are tricky), so if your bandwidth is limited I'd maybe say focus on the `Brush` / `Sankey` 🎉 ?

**Comment by geekplux** [comment]
So quick response and fixing, thank you @williaster , I will focus on the two components first, thanks
