### ISSUE TITLE
Where to start on Candlestick and related chart types?

### ISSUE THREAD

**Issue by twopirllc** [hshoff/vx#552]
Looks great!

What do you recommend on how to approach creating Candlestick and related chart styles?

Thanks

**Comment by williaster** [comment]
@hshoff made a [ethereum candlestick chart](https://github.com/hshoff/viewsource#2-ethereum-candlestick-chart) demo. It looks like the demo itself may no longer be live, but there's an image + source code. 

![image](https://user-images.githubusercontent.com/4496521/67977718-d748f780-fbd5-11e9-8d06-0a2fdbfc8600.png)

Not totally sure what you have in mind but you might also check out the [boxplot/violin example in the `/gallery`](https://vx-demo.now.sh/boxplot), or [this violin/boxplot example in `@data-ui`](https://williaster.github.io/data-ui/?selectedKind=xy-chart&selectedStory=Horizontal%20BoxPlot%20With%20ViolinPlot%20Example)

**Comment by twopirllc** [comment]
Thanks for responding. @williaster
