### ISSUE TITLE
Publish packages as beta

### ISSUE THREAD

**Issue by hellosmithy** [hshoff/vx#568]
Great work shifting many of the packages over to TypeScript. I was wondering if we could start to battle test them if they were published under a beta or alpha version to npm?

**Comment by williaster** [comment]
Yes! I will work on this in the next couple of days and track with this issue. Definitely want to battle test these. Converting the demo package should be a good test as well.

**Comment by williaster** [comment]
These are currently released now as `@vx/*@0.0.193-alpha.0` 🎉 Example codesandbox [here](https://codesandbox.io/s/romantic-montalcini-mmex5?fontsize=14&hidenavigation=1&theme=dark). 

Note that `grid`, `axis`, `legend`, and `stats` are still `JS` (track in the `TS` project associated with this issue) and `@vx/brush` is broken until #567 lands. I'm hoping to wrap up the remaining packages in the next ~week.

Thanks for testing, and **please** open issues for anything undesirable you encounter / PRs welcome if you want to help fix anything 🙏 Woot `TS`! 🤙

**Comment by hellosmithy** [comment]
Awesome thanks for the quick response! I'll start testing these and I'm more than happy to contribute if and when I can 👍

**Comment by hellosmithy** [comment]
@williaster Any chance you could also publish the latest changes from https://github.com/hshoff/vx/pull/567 too?

**Comment by williaster** [comment]
yes! trying to land the `@vx/legend` re-write in the next few minutes and will publish thereafter.

**Comment by williaster** [comment]
sorry for the delay, the types in `@vx/legend` were trickier than expected but that's merged. 

`0.0.193-alpha.1` is out now with all changes in master, the brush fix #567 and all packages re-written in TS 🎉 will likely now convert `vx-demo` to `ts` and release `0.0.193` after any needed fixes for that are in 👍

**Comment by williaster** [comment]
FYI I have a pretty big PR in progress for the `vx-demo` re-write: #579 . Lots of fixes being addressed and in linked PRs. Really hoping to wrap it up this week 🤞 🍀

**Comment by williaster** [comment]
#579 is in and TONS of fixes published under `0.0.193-alpha.2`, hopefully can land non-alpha `0.0.193` soon and call TS `v0` done 😄
