### ISSUE TITLE
Typo in Areas Demo?

### ISSUE THREAD

**Issue by seanpascoe** [hshoff/vx#572]
https://vx-demo.now.sh/areas
I'm having problems getting the bisector to work, so I have been following the Areas demo example code and stumbled across this. The following would error, right? Or is there yet another thing I'm missing?
```
const xStock = d => new Date(d.date);  // line 21
```
...then
```
d = x0 - xStock(d0.date) > xStock(d1.date) - x0 ? d1 : d0; // line 39
```
xStock(d0.date) // d.date is undefined
xStock(d1.date) // d.date is undefined

**Comment by hshoff** [comment]
Hi @seanpascoe, you are correct. This was updated in the [source](https://github.com/hshoff/vx/blob/master/packages/vx-demo/src/components/tiles/Areas.tsx#L65), but the changes haven't been reflected on the gallery example code. This will get fixed.

**Comment by hshoff** [comment]
Should be fixed now.
