### ISSUE TITLE
Update source code links in readmes to TS files

### ISSUE THREAD

**Issue by williaster** [hshoff/vx#591]
Need to make the changes in #588 for all packages

**Comment by dennisja** [comment]
Is anybody working on this or should I take it?

**Comment by williaster** [comment]
@dennisja if you'd like to work on it I'm happy to review a PR! 🙌

**Comment by dennisja** [comment]
I will start working on it today. Thanks.

**Comment by dennisja** [comment]
Hello @williaster 
I have looked through all the Readmes and they are up to date. The only readme remaining with a reference to a `.js` is the vx-scale readme as seen [here](https://github.com/hshoff/vx/blame/master/packages/vx-scale/Readme.md#L33). However, this references a valid [`js` file](https://github.com/hshoff/vx/blob/master/packages/vx-demo/src/components/charts/SimpleBar.js). Should I go ahead and migrate that file to typescript and make that link reference the typescript version?

**Comment by williaster** [comment]
Hi @dennisja ! Good to know we don't have a lot of references to specific files, really appreciate you digging into that more!

If you'd like to convert `vx-demo/src/components/charts/SimpleBar.js` to TS and update the readme, that'd be great!
