### ISSUE TITLE
[animations] develop story for animation + transitions

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#6]

**Comment by jacek213** [comment]
@hshoff is anyone working on this feature?

**Comment by williaster** [comment]
@jacek213 I believe we're still toying with different possible implementations of this and trying to figure out how opinionated to make the vx support. One issue is that there's not really a great story for animations in general in `react`. If you have any thoughts feel free to share 💭

**Comment by hshoff** [comment]
## Research

Current react animation landscape:

- [react-transition-group](https://github.com/reactjs/react-transition-group)
- [react-motion](https://github.com/chenglou/react-motion)
- [react-move](https://github.com/tannerlinsley/react-move)
- [data-driven-motion](https://github.com/tkh44/data-driven-motion)
- [velocity-react](https://github.com/twitter-fabric/velocity-react)

## Open questions

- how opinionated should vx be about animations?
- does vx need it's own animation library?
- what if an existing react codebase as already picked an animation lib? 
- should vx punt on animation into user land? (users decide from the list above and use what works best for them/already in use)
- should vx provide a recommended animation lib?
- will the upcoming react fiber release change the animation landscape/story in react land?

**Comment by denkristoffer** [comment]
Dont forget https://github.com/animatedjs/animated 🙂

**Comment by jacek213** [comment]
I've animated vx components with pure d3 transitions hooked up on `componentDidMount`... however that's probably not the proper way you'd want people to use transitions in vx 😆

**Comment by sghall** [comment]
I've been working on a more "d3" like interface for animations in React as well...

[Resonance](https://github.com/sghall/resonance) - Github
[NodeGroup](https://sghall.github.io/resonance/#/documentation/node-group) -Documentation
[Animated Bar Chart](https://sghall.github.io/resonance/#/redux-examples/states-by-age) - Example

It's a WIP.  I do like the approach vx is taking to SVG components.  Interested in seeing how animation piece develops. 

As you alluded to above, I think Fiber is going to be interesting for animations.  The priority levels for state updates are really needed to maintain good frame rates in React.  Thinking we should see a lot of contending APIs for animation stuff in react in the coming months.

**Comment by monsonjeremy** [comment]
I think one good way of doing this would be using D3 transition functions to create interpolators which can be used to incrementally update the state of the data over a given transition duration.

The downside to this is that it does put a constraint on how the data is formatted and how it is passed around. I also am not sure about performance for larger data sets or multiple components. 

I have some examples if you're interested in seeing.

**Comment by chrisdrackett** [comment]
https://popmotion.io as well ;)

they also maintain https://github.com/Popmotion/framesync which maybe could be used to support the transitions that @monsonjeremy mentions above? I've never animated anything in D3 so I basically don't know what I'm talking about :)

**Comment by sghall** [comment]
Looping back around on this.  Since my last comment [resonance](https://github.com/sghall/resonance) and [react-move](https://github.com/react-tools/react-move) have combined forces.  React-move 2.0 is fundamentally just a way to wire up D3 style transitions in react like is mentioned in this thread.  

The more difficult/interesting question has turned out how to make this into a understandable API and try to keep the flexibility you get in D3 (which has a steep learning curve).  Like to get more input, ideas, performance tweaks, examples, etc from others that are interested in working on this idea. Feel free to open an issue at [react-move](https://github.com/react-tools/react-move). Cheers.

**Comment by hshoff** [comment]
Seeing as there are many existing animation solutions out there in react-land, it seems best to defer to user choice rather than add another animation lib to the mix. This makes sense since vx should feel at home in any react app and you/your org might have already selected a react animation library so there would be no need to add another to the mix.

Happy to continue the discussion if you run into any unsupported use cases or if vx does something in particular that makes it hard to animate. 

So far I've seen animated charts built with vx using various animation libraries out there so I think we're ok here.

**Comment by techniq** [comment]
It would be nice to provide examples of using different libraries but this may be too much to put on the official [gallery](https://vx-demo.now.sh/gallery) or show bias/recommendation for a specific library, but maybe not?

Maybe just a bulleted list in the README or on the gallery page with links to some codesandbox examples, kind of like how downshift handles this?

**Comment by jeremejevs** [comment]
You should remove animations and transitions from the roadmap.
