### ISSUE TITLE
@vx/event needs documentation

### ISSUE THREAD

**Issue by cilphex** [hshoff/vx#601]
There is a `@vx/event` package but it has no description or examples. It might be helpful to add some documentation for it.

**Comment by pelagia** [comment]
+1

**Comment by williaster** [comment]
Totally agree, the TS re-write should help partially in _validating_ usage, but the docs are missing. We are planning some major improvements to documentation in the coming months with a release of `v1`

**Comment by hshoff** [comment]
Should be fixed now: https://vx-demo.now.sh/docs/event
