### ISSUE TITLE
JSX element type 'Brush' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by Shin--** [hshoff/vx#602]
I have been following the move to TypeScript and saw that the Brush component has finally gotten some examples. Using `"0.0.193-alpha.2"` I tried out some of the demo code. Some of it worked, but `Brush` did not. Using it leads to:

```
JSX element type 'Brush' is not a constructor function for JSX elements.
  Type 'Brush' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.ts(2605)
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
```

The issue here is the import of `React` inside `Brush.d.ts`: 
`import React from 'react';`

React apparently has no default export and TypeScript does not like or understand this, unless you set `"allowSyntheticDefaultImports": true`

`import * as React from 'react';` would be the correct import here that works and without setting this. Other typings import React the same way but didn't cause me any trouble. Still, maybe all imports of React should be adjusted.

Since I suck at TypeScript I could be wrong about the typings.

This Stackoverflow thread explains some of it:
https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react

**Comment by williaster** [comment]
Thanks for testing out `Brush` and highlighting this issue @Shin--!  🙌 I'll do some more digging to verify the proposed `import * as React from 'react'` fix, and track with this issue 👍

**Comment by williaster** [comment]
After discussing with some folks and reading more, I'm going to close this as _won't fix_. **Our general recommendation is to set `"allowSyntheticDefaultImports": true`**, which should fix this. From the docs:

> Allow default imports from modules with no default export. This does not affect code emit, just typechecking

While your proposal of using a `*` / namespace import (`import * as React from 'react'`) would also work, the TypeScript community is moving away from this pattern. This [SO post](https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file) gives more details about why these flags exist, and describes some of the limitations/issues with `*` namespace imports.

**Comment by wuzzeb** [comment]
Hi, I just hit this exact error (but with Text) since I didn't have allowSyntheticDefaultImports set.  I'm fine setting it, but perhaps a note can be added to the documentation?
