### ISSUE TITLE
I want to limit number of ticks on a area chart using scaleLog()

### ISSUE THREAD

**Issue by vipul-08** [hshoff/vx#603]
I want to achieve something which is possible in d3v5 as answered on https://stackoverflow.com/questions/52883663/limit-number-of-ticks-on-a-area-chart-using-d3-scalelog

But I didn't got anything related in the vx documentation..

**Comment by williaster** [comment]
Hi @vipul-08 👋 thanks for checking out `vx`! As that post says:

> Note that the number of ticks cannot be customized (due to the nature of log scales)

So I think the recommendation is to simply customize the `tickFormat`, returning empty strings for any values you don't want. [Here is an example of that with `vx`](https://codesandbox.io/embed/xoo6kkkynq?fontsize=14&hidenavigation=1&theme=dark).

There is also a complete render override hook where you can draw the entire axis yourself by passing a [`children` `renderFunction`](https://github.com/hshoff/vx/blob/master/packages/vx-axis/src/axis/Axis.tsx#L85). Using that approach you could decide whether to render tick line at all.

**Comment by vipul-08** [comment]
Thanks for the information @williaster

**Comment by vipul-08** [comment]
```
tickFormat: v => (String(v)[0] === "1" ? v : ""),
```

this doesn't work for values in range 0 to 1. The graph is reversed in this case
