### ISSUE TITLE
@vx/scales could use a Square-Root scale

### ISSUE THREAD

**Issue by cilphex** [hshoff/vx#604]
d3 supports a [square-root scale](https://github.com/d3/d3-scale#scaleSqrt), and it would be nice for VX to have something reflecting that.

d3's square-root scale is a convenience method that is a shortcut for a power scale with specific parameters, so achieving the desired effect may already be possible with the power scale in VX. But it would be nice to have that same shortcut for a common use case.

**Comment by williaster** [comment]
👋 @cilphex thanks for checking out `vx`! This sounds reasonable, I'd be happy to review a PR if you or anyone else would like to add this! I think adding a new scale that simply sets the needed `power-scale` parameters would be a fine solution.

**Comment by dennisja** [comment]
Raised the same issue some time back (https://github.com/hshoff/vx/issues/411) I can go ahead and work on this if no one is working on it

**Comment by dennisja** [comment]
@cilphex are you working on this?
If not, I can go ahead and work on it this week
