### ISSUE TITLE
Confusing examples, possible documentation improvements

### ISSUE THREAD

**Issue by davalapar** [hshoff/vx#611]
Welp, this project looks promising as hell but I gotta say it gents the onboarding process is quite a pain in the ass. Documenting this so 1.) newcomers can see what's up, and 2.) serve as additional reference for future PR's.

- [ ] Guides at https://vx-demo.now.sh/ links to outdated articles at https://medium.com/vx-code which does not work with the current version anymore.
- [ ] https://vx-demo.now.sh/areas
  - [ ] Embedded code returns an error of undefined margin object
  - [ ] Could be improved by providing example with react-hooks + proper prop-type checks
  - [ ] `Error: <line> attribute y2: Expected length, "NaN".`

**Comment by davalapar** [comment]
@hshoff silly question but where can I find the source files for https://vx-demo.now.sh/areas? Can't seem to find them at https://github.com/hshoff/vx and https://github.com/hshoff?tab=repositories

**Comment by PascalSenn** [comment]
@davalapar  I think the area source files are here: 
https://github.com/hshoff/vx/tree/master/packages/vx-shape

The documentation of VX just got some love. @williaster  and @hshoff  just rewrote the whole package in typescript.  The also update the documentation with the most recent typescirpt version. 
It's just not yet published. You can track the work here:
https://github.com/hshoff/vx/projects/2

If you want to help the last issue also concerning documentation is this one :) 
https://github.com/hshoff/vx/issues/591

**Comment by hshoff** [comment]
@davalapar gallery example source lives here: https://github.com/hshoff/vx/tree/master/packages/vx-demo/src/components/tiles

We've had some trouble syncing the source with the example code on the gallery site. As mentioned in https://github.com/hshoff/vx/issues/601#issuecomment-578267408 this will get addressed in the coming months with v1. 

Going to close this issue for now as @williaster and I are tracking this already and working on improvements. Happy to re-open or feel to create other issues for improvements you'd like to see.

**Comment by williaster** [comment]
FYI duplicate demo + demo source code was fixed with #637, and the code sandox refactor is being tracked in #624
