### ISSUE TITLE
withParentSize no longer delays rendering until size is known

### ISSUE THREAD

**Issue by dson** [hshoff/vx#619]
Previously, `withParentSize` would only render its children when the size was known. However, since commit https://github.com/hshoff/vx/commit/b05a17fbc92a698b036c64886b8679ee2475be0e, the children are initially rendered without size. This breaks components that expect `parentWidth` and `parentHeight` to be available.

The problem is that the state is initialized with `undefined`, while the render method checks for `null`.

**Comment by williaster** [comment]
@dson thanks for checking out `vx` and reporting this issue + triaging, I will post a fix asap 👍
