### ISSUE TITLE
(vx-demo/vx-brush) Brush drag has offset when group has margin. 

### ISSUE THREAD

**Issue by Shin--** [hshoff/vx#620]
The brush positioning seems to be affected by the margin of the group surrounding it, which leads to the area being drawn with an offset from where your cursor is. I noticed this in my own code, thought that I must be doing something wrong, but the example (which is quite recent) has the same issue: https://github.com/hshoff/vx/blob/master/packages/vx-demo/src/components/tiles/Brush.tsx

I am not sure if this is a bug (if it is at all) with the Brush package or if Drag is not working as intended (as the values come from there).

![ufOwXXrGjC](https://user-images.githubusercontent.com/4537422/73676925-8c97b980-46b5-11ea-8ff6-6913b951820d.gif)

**Comment by williaster** [comment]
thanks for the bug report @Shin-- 🙌 will try to triage if it's brush vs drag but may not have time to do this for a few days, will happily accept any help/fixes in the mean time!

**Comment by dennisja** [comment]
Hello @williaster and @Shin-- 
I have been trying to play with the brush to investigate the cause of this issue and see whether I can fix it, however, my initial conclusion is that it is not the problem with the brush, It is the problem with the function that handles what happens on brush change and specifically this [line](https://github.com/hshoff/vx/blob/368b57b8856c1e0f845380c7330be3cf2c866bf1/packages/vx-demo/src/components/tiles/Brush.tsx#L125) looks problematic to me as it ignores the bound values that are equal to x or y. 

I have made an enhancement which you can play within this [sandbox](https://codesandbox.io/s/github/dennisja/vx-playground) or clone and run from this [repo](git@github.com:dennisja/vx-playground.git)

Play with it and if you too confirm that it was a mistake in the filter function, I can go ahead and raise a PR to update that example.

**Comment by geekplux** [comment]
oops, I think it's a margin issue, let me check it.
