### ISSUE TITLE
Zoom constrain holds old prop reference

### ISSUE THREAD

**Issue by mitchellwarr** [hshoff/vx#622]
In the Zoom package, the component will only keep, remember, and use the first function reference to the constrain prop. If you pass constrain as a useCallback, then when the function updates, the Zoom component does not use the new reference.

This is because the Zoom class creates a direct reference to the this.props.constrain function on mount and never updates it.

**Comment by mitchellwarr** [comment]
Created a PR fix for this that is awaiting review

**Comment by williaster** [comment]
@mitchellwarr thanks for reporting the issue and the fix 🙌  I'll try to review ASAP/end of day today.

**Comment by mitchellwarr** [comment]
Thank you @williaster. This will be a big help

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/578
