### ISSUE TITLE
[docs] link out to codesandbox from examples

### ISSUE THREAD

**Issue by williaster** [hshoff/vx#624]
We've gotten a lot of requests to link out to codesandbox from demo examples. 

This should be pretty straight forward using their github API https://codesandbox.io/docs/importing#import-from-github 

This will require refactoring each demo example to be a standalone package.

**Comment by geekplux** [comment]
Sounds good and useful for promotion, and I think tutorials(#11 ) or guides are needed if we want more users, we could provide these docs embedding codesandbox https://codesandbox.io/docs/embedding#example-embeds

**Comment by williaster** [comment]
Enumerating the examples to be ported / tracking status here cc @pedroapfilho

- [x] Axis #642 
- [ ] Areas
- [ ] BarGroup
- [ ] BarGroupHorizontal
- [ ] Bars
- [ ] BarStack
- [ ] BarStackHorizontal
- [ ] Brush
- [ ] Chord
- [ ] Dendrograms
- [ ] Dots
- [ ] Drag-i
- [ ] Drag-ii
- [ ] Geo-Custom
- [ ] Geo-Mercator
- [ ] Glyphs
- [ ] Gradients
- [ ] Heatmap
- [ ] Legends
- [ ] LineRadial
- [ ] Lines
- [ ] LinkTypes
- [ ] Network
- [ ] Pack
- [ ] Patterns
- [ ] Pies
- [ ] Polygons
- [ ] Radar
- [ ] Responsive
- [ ] Stacked-Areas
- [ ] Statsplot
- [ ] Streamgraph
- [ ] Threshold
- [ ] Treemap
- [ ] Trees
- [ ] Voronoi
- [ ] Zoom-i
