### ISSUE TITLE
Is there a way to draw ticksLabel on axisBottom on two line ?

### ISSUE THREAD

**Issue by altrang** [hshoff/vx#629]
Hello, 
I m new to vx and i m trying to draw a graph where tickLabel on axisBottom are on two line (day of week and day number under it)
Im not sure there is a way to handle it.
If you know a way to handle this case please give me some clue !
Thank you !

**Comment by williaster** [comment]
Sorry for the delay @altrang ! This should be possible, do you have an example that you are trying to reproduce? (that could help me recommend a specific solution)

**Comment by hshoff** [comment]
Hi @altrang, I'm going to close this for now. Feel free to re-open with a link to example code and we can help take a look.
