### ISSUE TITLE
Publish @vx/tooltip with `useTooltip` hook

### ISSUE THREAD

**Issue by amytych** [hshoff/vx#633]
Hi! 👋

Seems that the `useTooltip` hook is [documented](https://github.com/hshoff/vx/tree/master/packages/vx-tooltip#usetooltip-for-functional-components) but not yet published on npm, would be great to get it out there if possible 👍 

Thanks for all the great work! 🙏

**Comment by williaster** [comment]
yes! will release by EOD and use this issue to track. 

also working on auto releases so there isn't a delay when features are merged (#623), this is complicated for a few reasons so likely won't land for several weeks but FYI.

**Comment by williaster** [comment]
Done 🎉 see [the release](https://github.com/hshoff/vx/releases/tag/v0.0.195)
