### ISSUE TITLE
tickFormat for scaleLog

### ISSUE THREAD

**Issue by vipul-08** [hshoff/vx#636]
```tickFormat: v => (String(v)[0] === "1" ? v : ""),```

for scaleLog
this doesn't work for values in range 0 to 1. The graph is reversed in this case

**Comment by hshoff** [comment]
Log scales can't include `0`. More info here: https://github.com/d3/d3-scale#log-scales
example here: https://codesandbox.io/s/unruffled-goldstine-2btki?file=/Example.tsx:2180-2380

![image](https://user-images.githubusercontent.com/339208/89109131-73758880-d40c-11ea-9fa0-e7b2f9c34290.png)
