### ISSUE TITLE
Travis build doesn't run lint step

### ISSUE THREAD

**Issue by ptmx** [hshoff/vx#638]
It looks like the intention of the Travis config is to run tests and lint in parallel:

https://github.com/hshoff/vx/blob/6bdca40d9b7150b307328f1c07543b06bb6c5fcd/.travis.yml#L14-L19

However, the actual build only runs the default test script, i.e., it runs `yarn test` [since `yarn.lock` is present](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#yarn-is-supported).  `yarn lint` doesn't get executed at all.

For example, see the logs from the latest build on `master`: https://travis-ci.org/hshoff/vx/builds/655661819.  The build runs `yarn test` instead of `yarn run jest -w 4`  as specified in the config file, and omits the `yarn lint` step altogether.

One option is to override the default `script`:

```
script:
  - yarn run jest -w 4
  - yarn run lint
```

Although this wouldn't run those steps in parallel.  Alternatively I'm sure there's a way to accomplish this with the existing build matrix too, although from skimming the docs for a bit it's not immediately obvious to me how the `script` and `jobs` keys interact.

**Comment by williaster** [comment]
Thanks for flagging this @ptmx and digging into the root-cause (I didn't know about the default `yarn test` logic), this explains some strange observations on travis. I'll dig into docs more to see if there's a solid solution for running it all in parallel 👍

**Comment by ptmx** [comment]
@williaster I ended up digging into it a bit more and opening https://github.com/hshoff/vx/pull/640 to fix this.  I found that the `matrix` and `jobs` keys conflicted with each other, but once I consolidated those two configs then Travis correctly ran the two jobs in parallel instead of the default `yarn test` 👍

**Comment by williaster** [comment]
🙉  sorry I missed that, I converged on the same thing with #641, but I'll close that in favor of yours.

One other bit of info I found after talking to some folks was that the parallel mode can actually be _slower_ because it has to completely setup and yarn install the project for each parallel job. In that case we might actually want to use a single `test` step with the `script: yarn run jest -w 4 && yarn run lint`

I'll try this to see if it's faster for vx in #641 just to compare the times, and circle back 👍

**Comment by ptmx** [comment]
> 🙉 sorry I missed that, I converged on the same thing with #641, but I'll close that in favor of yours.
> 
> One other bit of info I found after talking to some folks was that the parallel mode can actually be _slower_ because it has to completely setup and yarn install the project for each parallel job. In that case we might actually want to use a single `test` step with the `script: yarn run jest -w 4 && yarn run lint`
> 
> I'll try this to see if it's faster for vx in #641 just to compare the times, and circle back 👍
> 
> UPDATE: left a speed comparison comment in #640

Glad to hear we ended up in the same place! 😄
