### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by crackcomm** [hshoff/vx#64]
Is it currently possible for example in https://vx-demo.now.sh/trees to make A3 parent of C1 or C1 parent of B1?

I want to be able to represent information flow between multiple neurons nodes being neurons but also dendrites and axon terminals (inputs and output).

**Comment by hshoff** [comment]
Hi @crackcomm, thanks for checking out vx!

Unfortunately no, adding `C1` as a child to `A3` results in:

<img width="838" alt="screen shot 2017-06-13 at 5 06 31 pm" src="https://user-images.githubusercontent.com/339208/27109990-0b870d4e-505b-11e7-9eb8-349bbbea3d1f.png">

We'll need to add either a `network` component to `@vx/hierarchy` or create a new package `@vx/network`... haven't decided which yet. Sorry vx doesn't support this yet :/

**Comment by crackcomm** [comment]
@hshoff I will certainly use vs when It'll be capable of doing that, thanks.

**Comment by crackcomm** [comment]
Im not sure that should be a part of core but a grouping like in tensorboard so you can expand the graph will be very useful when visualizing large graphs ![](https://i.stack.imgur.com/hXoW9.png)

**Comment by hshoff** [comment]
Progress here: https://github.com/hshoff/vx/pull/113 will be available in `v0.0.135`

**Comment by hshoff** [comment]
Closing because we published `@vx/network` with `<Graph />, <Node />, and <Link />` in `v0.0.135`. Additional features/requests for graphs should go in a new issue for us to track.
