### ISSUE TITLE
Scaling issue in IE 11 in ScaleSVG component

### ISSUE THREAD

**Issue by mohammed-adil** [hshoff/vx#646]
Hey @hshoff @williaster, I'm new to `vx` and pardon me if I'm raising an unnecessary issue. 
I've been facing issue with SVG graph not able to scale up to the viewport `width` and `height` in IE 11

Here's how it looks in IE 11 (shrinked)
![Screenshot 2020-03-09 at 9 33 27 AM](https://user-images.githubusercontent.com/31363829/76181980-18d35a00-61e9-11ea-97d7-89564556c98d.png)

Whereas in Chrome/Firefox graph is scaled up to the available viewport size (which is fine for me)

Here's my Graph component
```
class Graph extends Component {
  handleMouseOver = (e, d) => {
    const coords = localPoint(e.target.ownerSVGElement, e)
    this.props.showTooltip({
      tooltipLeft: coords.x,
      tooltipTop: coords.y,
      tooltipData: d
    })
  }

  render () {
    const { tooltipData, tooltipLeft, tooltipTop, tooltipOpen, hideTooltip } = this.props

    const data = [
      {
        label: 'Its fine- whatever works, right?',
        value: '25'
      },
      {
        label: 'I dont mind them but never used much',
        value: '45'
      },
      {
        label: 'I preferred to not use the dummy as much as possible',
        value: '55'
      },
      {
        label: 'I would never use a dummy',
        value: '35'
      }
    ]

    const width = 1000
    const height = 600

    // accessors return the label and value of that data item
    const x = d => d.label
    const y = d => d.value

    // bounds for bar graph
    const xMax = width
    const yMax = height - 100

    // scales for bar graph
    const xScale = scaleBand({
      rangeRound: [0, xMax],
      domain: data.map(x),
      padding: 0.2
    })
    const yScale = scaleLinear({
      rangeRound: [0, yMax],
      domain: [Math.max(...data.map(y)), 0]
    })

    return (
      <>
        <ScaleSVG width={width} height={height}>
          <rect width={width} height={height} fill='#fff' />
          <Group top={25} left={55}>
            <AxisLeft
              left={10}
              scale={yScale}
              stroke='#1b1a1e'
              fontSize={10}
            />
            {data.map((d, i) => {
              const label = x(d)
              const barWidth = xScale.bandwidth()
              const barHeight = yMax - yScale(y(d))
              const barX = xScale(label)
              const barY = yMax - barHeight
              return (
                <Bar
                  key={`bar-${label}`}
                  x={barX}
                  y={barY}
                  width={barWidth}
                  height={barHeight}
                  fill='#1890ff'
                  onMouseOver={e => this.handleMouseOver(e, d)}
                  onMouseOut={hideTooltip}
                />
              )
            })}
            <AxisBottom
              scale={xScale}
              top={yMax}
              labelOffset={15}
              stroke='#1b1a1e'
              fontSize={10}
            />
          </Group>
        </ScaleSVG>
        {tooltipOpen && (
          <TooltipWithBounds
            key={Math.random()}
            top={tooltipTop}
            left={tooltipLeft}
          >
            {tooltipData.label} <strong>{tooltipData.value}%</strong>
          </TooltipWithBounds>
        )}
      </>
    )
  }
}

export default withTooltip(Graph)
```

Did I miss something with `ScaleSVG` for it to work properly on IE 11?
Also, I saw that even with us passing width and height to ScaleSVG, the rendered SVG is not actually using `width` and `height` attributes. Can anyone tell me why?

I'm a bit confused, cause I couldn't find proper use case in the docs.

**Comment by hshoff** [comment]
> Internet Explorer applies the standard default 300x150 size. However, other browsers will apply `{ width: 100%; height: auto; }` by default if the image has a `viewBox`; this behaviour is not defined in any specification.
- https://css-tricks.com/scale-svg/

Could you try adding css to set the svg container to make width/height? I don't have access to IE11 to test.

Here's the `<ScaleSVG />` source: https://github.com/hshoff/vx/blob/master/packages/vx-responsive/src/components/ScaleSVG.tsx#L23 it could be related to the parent div not filling all available space or it could be the svg not filling the space.

**Comment by mohammed-adil** [comment]
Thanks @hshoff, it's mostly related to SVG not able to fill 100% of parent width and height, I was able to fix this by defining SVG width & height just for IE 11.

Note: It didn't work when I specified the parent div width/height
