### ISSUE TITLE
BarGroup with negative and positive values

### ISSUE THREAD

**Issue by alex-dolbik** [hshoff/vx#662]
Hello, is it possible to build Chart with Bar Groups which have positive and negative values?

Currently it looks like this:

![image](https://user-images.githubusercontent.com/10628158/78976434-d3bf8200-7b1e-11ea-8090-5ce5f8f233e9.png)

But ideally it should be something like this:

![image](https://user-images.githubusercontent.com/10628158/78976447-d91ccc80-7b1e-11ea-988b-16ee6b333a10.png)

**Comment by techniq** [comment]
@alex-dolbik You want to use a diverging stack offset. Here is the canonical d3 [example](https://observablehq.com/@d3/diverging-stacked-bar-chart) or a simpler [example](https://bl.ocks.org/LemoNode/91c6e989696caa909dc2333cde0d9657).

In short, you want to pass `stackOffsetDiverging` to `offset` on `d3.stack()`.  For example:

```js
 d3.stack()
  .keys(...)
  .offset(d3.stackOffsetDiverging)
```

vx has a helper util in [@vx/shape](https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/util/stackOffset.ts) to do this by name, so you can also use

```jsx
import { stackOffset } from '@vx/shape';

 d3.stack()
  .keys(...)
  .offset(stackOffset('diverging'))
```

This makes it more convenient if you want to pass `offset` as a prop / string instead of the function.

**Comment by williaster** [comment]
@techniq is there an equivalent for this for bar group (not stack)? was just encountering this with the `xychart` and I think the math in the component just doesn't handle this.

**Comment by techniq** [comment]
@williaster Hmm... sorry I misread this as stack and not group.

I just check my bar group charts and they support negative values...

![image](https://user-images.githubusercontent.com/177476/85652693-6e892080-b679-11ea-8c14-b439a8cf1cba.png)

I don't appear to do anything special for negative values...

```tsx
// ...

const yScale = scaleLinear<number>({
  rangeRound: [yMax, 0],
  domain: [
    min([
      yScaleZero ? 0 : undefined,
      ...data.map((d, i) => min(keys.map(key => y(d, key, i))))
    ]),
    max([
      yScaleZero ? 0 : undefined,
      ...data.map((d, i) => max(keys.map(key => y(d, key, i))))
    ])
  ],
  nice: true,
  ...yScaleProps
});

// ...

<BarGroup
  data={
    // Apply `y` value accessor to data since vx currently does not support it (https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/BarGroup.js#L155).
    // Similar to `value` accessor for stack
    data &&
    data.map((group, i) => {
      const item = { ...group };
      keys.forEach(key => (item[key] = y(item, key, i)));
      return item;
    })
  }
  keys={keys}
  height={yMax}
  x0={x0}
  x0Scale={x0Scale}
  x1Scale={x1Scale}
  yScale={yScale}
  color={color ?? (() => blue[500])}
>
  {(barGroups: any) => {
    return barGroups.map((barGroup: any, barGroupIndex: number) => {
      return (
        <Group
          key={`bar-group-${barGroup.index}-${barGroup.x0}`}
          left={barGroup.x0}
        >
          {barGroup.bars.map((bar: any, barIndex: number) => {
            const barObj = getVerticalBarInfo({
              x: bar.key,
              y: bar.value,
              xScale: x1Scale,
              yScale,
              data,
              group: barGroup,
              groupData: data[barGroupIndex]
            });

            return (
              <React.Fragment key={`bar-${bar.key}`}>
                <VerticalBarShape
                  bar={barObj}
                  index={barIndex}
                  xScale={x1Scale}
                  yScale={yScale}
                  color={bar.color}
                  barProps={barProps}
                  barTargetProps={barTargetProps}
                  showTooltip={showTooltip}
                  hideTooltip={hideTooltip}
                />
                {renderLabel &&
                  renderLabel({
                    bar: barObj,
                    value: barObj.value
                  })}
              </React.Fragment>
            );
          })}
        </Group>
      );
    });
  }}
</BarGroup>
```

Actually when I looked at the impl for `getVerticalBarInfo()`, I do some special handling if the value is less than `0`...

```jsx
export function getVerticalBarInfo({
  data,
  x,
  y,
  xScale,
  yScale,
  group,
  groupData,
}) {
  const yValue = y || 0;
  const [yDomainMin] = yScale.domain();

  return {
    x: xScale(x),
    y: yScale(yValue > 0 ? yValue : 0),
    width: xScale.bandwidth(),
    height: Math.abs(
      yScale(yValue) -
        (yValue > 0 ? yScale(Math.max(0, yDomainMin)) : yScale(0))
    ),
    value: y,
    data,
    group,
    groupData,
  };
}
```

- If yValue > 0:
  - `y` = `yScale(yValue)`
  - `height` = `Math.abs(yScale(yValue) - yScale(Math.max(0, yDomainMin)))`
- If yValue <= 0:
  - `y` = `yScale(0)`
  - `height` = `Math.abs(yScale(yValue) - yScale(0))`

This d3 example might help as well:
https://bl.ocks.org/gurjeet/83189e2931d053187eab52887a870c5e

**Comment by mamo-muj** [comment]
@techniq I saw an interesting thing in your screenshot which is something I'd like to achieve as well - the axis line with the 0 value stroke fill is different from the rest of the grid lines. How did you achieve that? My charts have positive and negative values and so I'd like to change the fill color for it to be differentiated from the rest

![CleanShot 2024-01-02 at 15 18 24](https://github.com/airbnb/visx/assets/86906789/26e36cd8-332f-4b6c-86cf-d58e0d689505)

**Comment by techniq** [comment]
@mamo-muj Just draw a `<line>` using `yScale(0)` for `y1`/`y2`

```jsx
<line
    x1={0}
    x2={xMax}
    y1={yScale(Math.max(0, yDomainMin))}
    y2={yScale(Math.max(0, yDomainMin))}
    stroke="black"
  />
```

Here it is with a little more context...

![image](https://github.com/airbnb/visx/assets/177476/2169db9a-eea3-4a9c-a718-c534bbdbc526)


Nowadays I use Svelte (and wrote [LayerChart](https://www.layerchart.com/docs/examples/Columns/)).  To do similar, you just add a `<Rule y={0} />`. 

![image](https://github.com/airbnb/visx/assets/177476/17260796-be0f-4188-b942-9f6e19104c36)

You could build something with visx as an abstraction.  See the `Rule` [docs](https://www.layerchart.com/docs/components/Rule/) as well as the [implementation](https://github.com/techniq/layerchart/blob/main/packages/layerchart/src/lib/components/Rule.svelte).   Once again it's Svelte, but you can probably read the intent.  LayerChart uses [LayerCake](https://layercake.graphics/) to setup the chart context, which is similar to visx's [XYChart](https://airbnb.io/visx/docs/xychart).

Hope this helps
