### ISSUE TITLE
Pie Lines

### ISSUE THREAD

**Issue by libnine** [hshoff/vx#663]
Is there a way to make the lines in the pie charts more visible? Here's the code along with a screenshot:

```
  return (
    <>
      <svg width={width} height={height}>
        <LinearGradient 
          from="#b39cea" 
          to="#e99cea" 
          id="gradient"/>
        <rect width={width} height={height} fill="#fbc2eb" rx={14} />
        <Group top={height / 2} left={width / 2}>
          <Pie
            fill={`url('#gradient')`}
            centroid={(centroid, arc) => {
              const [x, y] = centroid
              return (
                <Label x={x} y={y}>
                  {arc.data.age_group}
                </Label>
              )
            }}
            data={data}
            outerRadius={radius - 125}
            pieValue={d => d.death_rate}
          />
        </Group>
      </svg>
    </>
  )
}

```

![Screen Shot 2020-04-11 at 10 40 40 AM](https://user-images.githubusercontent.com/31510420/79050768-147fcf80-7be1-11ea-9734-084bd009c3e9.png)

**Comment by williaster** [comment]
👋  @libnine, thanks for checking out `vx`. If you inspect the output of this in your browser you'll see that `Pie` arcs are created as `SVG` `path` elements. Depending on how you want to style your chart you could simply add a `stroke={colorVariable}` to your `<Pie />` to give something like

![image](https://user-images.githubusercontent.com/4496521/79184617-861a7200-7dc9-11ea-94af-2baf4f690bc3.png)

Alternatively, if you don't want an outline and want to differentiate segments spatially, you could tweak some of the underlying `d3` `pie` generator variables like `cornerRadius` or `padAngle`. See the [`Pie` demo codesandbox](https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/docs-v2/examples/vx-shape-pie) for an example.

![image](https://user-images.githubusercontent.com/4496521/79184786-fe813300-7dc9-11ea-9c99-926a8d944cb4.png)
