### ISSUE TITLE
useTooltip examples

### ISSUE THREAD

**Issue by libnine** [hshoff/vx#664]
I can't seem to find many (basically any) examples on `useTooltip`. Is it possible to get this added?

I'm aware of the [documentation](https://github.com/hshoff/vx/tree/master/packages/vx-tooltip#examples) but there are no working examples and it is quite vague.

**Comment by williaster** [comment]
Hi @libnine 👋 , thanks for checking out `vx`. We are actively working on improving the docs to make things easier to ramp up. For now this is all documented in the [`vx-tooltip` readme](https://github.com/hshoff/vx/tree/master/packages/vx-tooltip#usetooltip-for-functional-components).
