### ISSUE TITLE
gradients from demo don't show in Safari

### ISSUE THREAD

**Issue by jharris4** [hshoff/vx#68]
Nice work on the library!

Just thought I'd give a helpful tip, Safari doesn't support rgba colors for gradient stop attributes, so you need to remove the opacity on this line:

https://github.com/hshoff/vx/blob/11dd365aa1a60d354a3c015199ee549961edd6e4/packages/vx-demo/pages/areas.js#L62

I'd recommend changing the props for `LinearGradient` to also accept the fromOpacity and toOpacity.

I can't remember the exact post where I learned about this, but here's a relevant one:
https://stackoverflow.com/questions/31729206/svg-transparent-radial-gradient-in-safari-not-working

**Comment by hshoff** [comment]
Hi @jharris4, thanks for checking out vx and true! This was bugging me for a while, but the fix should be out for the current https://vx-demo.now.sh/gallery

I believe you're looking at an older commit. I updated this a bit ago for the transparent area gradient: https://github.com/hshoff/vx/blob/master/packages/vx-demo/components/tiles/area.js#L50

Will definitely add `fromOpacity` + `toOpacity` to `LinearGradient` and I'd like to also support `gradientTransform` so you can rotate your LinearGradient and do other transforms. 

This also reminds me, I need to add `RadialGradient`. 

Lots more coming for `@vx/gradient`

**Comment by hshoff** [comment]
fixed in https://github.com/hshoff/vx/pull/82

will track adding `RadialGradient` here https://github.com/hshoff/vx/issues/83

**Comment by rollasoc** [comment]
Gradients for me on iOS are showing as black,   

I have tried Linear Gradient
                          <LinearGradient
                                from='#0f73c1'
                                to='#0f609f'
                                id="levelgradient"
                                fromOpacity={0.3}
                                toOpacity={1}
                            />

as well as the built in gradients, tried on Chrome and Safari on iOS.  (using iOS 9.3.5)
Tried with and without the to/from Opacity.
Plus your gallery page doesn't load in iOS crashes with "An unexpected error has occurred" 

Any suggestions?
