### ISSUE TITLE
Could we make a vx-util?

### ISSUE THREAD

**Issue by Flaque** [hshoff/vx#69]
There's a couple repeated instances around VX that could probably be put into a separate package. 

For example, [additionalProps in heatmap](https://github.com/hshoff/vx/blob/936d58ab684e65434d5332a5c9c479a36d86d376/packages/vx-heatmap/src/util/additionalProps.js) and [additionalProps in shape]. 

Is there any reason why these aren't in their own package?

**Comment by hshoff** [comment]
> Is there any reason why these aren't in their own package?

Just laziness at the moment. Good point, we should do this. 

There's some more work I'd like to do with `additionalProps` so it's more explicit which props get passed on. And I might revisit the api for how data get's passed to thunks re: https://github.com/hshoff/vx/issues/50#issuecomment-306431147 but I haven't gotten to these two things just yet.
