### ISSUE TITLE
TooltipWithBounds types do not have the new unstyled props

### ISSUE THREAD

**Issue by tbassetto** [hshoff/vx#691]
The `<TooltipWithBounds />` component [redefines `TooltipProps`](https://github.com/hshoff/vx/blob/da9f09df06ca16e534d95027812e0a74f7488a14/packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx#L21) instead of inheriting it from [`<Toolip/>`](https://github.com/hshoff/vx/blob/da9f09df06ca16e534d95027812e0a74f7488a14/packages/vx-tooltip/src/tooltips/Tooltip.tsx#L4) and thus TypeScript is complaining that it doesn't recognize `unstyled`.

**Comment by williaster** [comment]
Thanks for flagging this @tbassetto. I'm happy to review a PR if you/others are up for it. 

I think to fix it properly we'd need to not just inherit the `types` from `Tooltip`, but remove the `styles` set by `TooltipWithBounds` and instead pass `top` and `left` to `Tooltip` so it can handle the merging of `styles` or not applying them if `unstyled` is set.
