### ISSUE TITLE
the drag moudel is nothing

### ISSUE THREAD

**Issue by jockw** [hshoff/vx#72]
Are there  any method to copy drag of d3 and used in vx?

**Comment by Flaque** [comment]
This is coming <3

**Comment by hshoff** [comment]
Yup! It's in the works, but nothing is published just yet. Need to get `@vx/brush` `@vx/zoom` and `@vx/drag` all working nicely. Will have it done for v1, but focusing on `@vx/legend` at the moment.

**Comment by hshoff** [comment]
closing in favor of https://github.com/hshoff/vx/issues/8
