### ISSUE TITLE
[pattern] add support for left-to-right diagonal lines

### ISSUE THREAD

**Issue by jithureddy** [hshoff/vx#723]
Diagonal Lines are from top right to bottom left, but want to change it to top left  to bottom right 

**Actual:**
![image](https://user-images.githubusercontent.com/5911189/82319460-84942900-99c9-11ea-8976-ff4a0b780b88.png)

**Desired:** 
![image](https://user-images.githubusercontent.com/5911189/82319600-c1f8b680-99c9-11ea-8c55-459bf4cd4e17.png)

How can we achieve this?

**Comment by hshoff** [comment]
Currently we don't support tr->bl. This would be a good addition.

This is possible today by providing a custom path to <Pattern /> like so:

```jsx
<Pattern id={id} width={width} height={height}>
  <path d={diagonalRightToLeft(height)} />
</Pattern>
```

```typescript
function diagonalRightToLeft(size: number): string {
  const half = size / 2;
  return `M 0,0 l ${size},${size}
    M ${-size / 4},${(3/4) * size} l ${half},${half}
    M ${(3/4) * size},${-size / 4} l ${half},${half}`;
}
```

Until we add support for this top left to bottom right diagonal orientation to `@vx/pattern` the above should be used as a workaround.

Hope this helps!

**Comment by williaster** [comment]
Agree this would be a good add! Happy to review PRs if anyone is interested in adding it 😄

**Comment by jithureddy** [comment]
@williaster I can create a PR for this over the weekend

**Comment by dennisja** [comment]
@jithureddy did you open it yet. I had started working on one today before I saw your comment 🤦

**Comment by jithureddy** [comment]
@dennisja Sorry, Please feel free to work on it. I am working on something else.

**Comment by dennisja** [comment]
Been a bit busy this week. I can work on it next week
