### ISSUE TITLE
bug: tooltip y-positioning calculation with scroll

### ISSUE THREAD

**Issue by timhwang21** [hshoff/vx#733]
Hello 👋 it looks like there is an issue with how the y-position of tooltips is calculated. This can be replicated in [this demo from the gallery](https://vx-demo.now.sh/barstack). Specifically, the y coordinate seems to not properly for scrolling.

Here is a short video showing this: https://gfycat.com/silkyjitteryafricancivet

If there is a known fix / workaround, please let me know! Else, if some codebase guidance can be provided I'd happily work on this. Cheers!

**Edit:** I'm dumb, this is actually just a problem with the demo! Specifically the lines:

```typescript
onMouseMove={(event) => {
  if (tooltipTimeout) clearTimeout(tooltipTimeout);
  // event.clientY here -- need to account for scroll
  const top = event.clientY - margin.top - bar.height;
  const offset = (xScale.paddingInner() * xScale.step()) / 2;
  const left = bar.x + bar.width + offset;
```

**Comment by vitto-moz** [comment]
I had something similar
have it resolved with `containerBounds`

```
const {
    containerRef,
    containerBounds, // <== here it is
    TooltipInPortal,
  } = useTooltipInPortal();
```

```
     onMouseMove={(arcDatum, event) => {
                    if (tooltipTimeout) clearTimeout(tooltipTimeout);
                    const top = event.clientY - containerBounds.top; // <== use it as an offset
                    const left = event.clientX;
                    showTooltip({
                      tooltipData: arcDatum,
                      tooltipTop: top,
                      tooltipLeft: left,
                    });
                  }}
```
