### ISSUE TITLE
Discontinuous Data

### ISSUE THREAD

**Issue by IIAmbitionsII** [hshoff/vx#738]
I have a graph that could have missing line data. For example,  say there is a line from 1 PM to 4 PM but 5 PM is missing and It starts back at 6 PM. Currently it just draws a straight line from 4 to 6. Is there a way to stop it from drawing so there would be a gap in between 4 to 6 for this example.

**Comment by hshoff** [comment]
Yes, you can use the [`defined`](https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/LinePath.tsx#L13) prop function to create discontinuous line segments. More info from d3 documentation: https://github.com/d3/d3-shape#line_defined

```jsx
const data = [
  { time: '4pm', value: 1 },
  { time: '5pm', value: undefined },
  { time: '6pm', value: 2 }
]

<LinePath
  data={data}
  x={d => dateFn(d.time)}
  y={d => d.value}
  defined={d => !isNaN(d.value)}
  // ...
/>
```
