### ISSUE TITLE
Bar graphs not lining up with date scale. Squishing?

### ISSUE THREAD

**Issue by IIAmbitionsII** [hshoff/vx#739]
I am graphing a days worth of 5 minute data here and I have found that it only has this "squishing" effect (where there are gaps at the start and end of the time scale) on bar graphs that have a lot of data.
![image](https://user-images.githubusercontent.com/25162589/83625738-6f3f0300-a562-11ea-9e03-230eee99781a.png)

Is there a way to line it up with time scale correctly?

**Comment by hshoff** [comment]
Could you provide a [codesandbox](https://codesandbox.io) or similar reproducing the problem? This will help us assist you.

**Comment by IIAmbitionsII** [comment]
@hshoff Here is example on codesandbox - https://codesandbox.io/s/serene-engelbart-zwxgy?file=/src/App.js

In App.js if you comment out line 4 and un-comment line 5 you can see the difference that little data shows bars normally but a lot of data shows bars with that squish effect,

**Comment by hshoff** [comment]
The extra space is due to using [`rangeRound()`](https://github.com/d3/d3-scale#band_rangeRound) which will apply [rounding](https://github.com/d3/d3-scale#band_round).

To remove the added space from rounding on Line#134: 
```diff
- dateScale.rangeRound([0, xMax]);
+ dateScale.range([0, xMax]);
```

**Comment by IIAmbitionsII** [comment]
Thank you so much! It worked! Again thank you for your help on this question and the other one I had up!

**Comment by hshoff** [comment]
No problem. Thanks for checking out vx!
