### ISSUE TITLE
Responsive axislabeloffset based on ticklabelwidth

### ISSUE THREAD

**Issue by samjbmason** [hshoff/vx#743]
More of a question than a issue but wondered if anyone had dealt with the following scenario. 

I’m building a line chart and the values along the y axis can vary wildly between call sites. I wonder if there is a way of getting the largest width of tick labels from the y axis and use that value to add the appropriate amount of space to the axis label as well as any margin needed to add to the position of the x axis so that it doesn’t get clipped from the edge of the svg element. 

Any help or links would be great.

**Comment by williaster** [comment]
@samjbmason for the label, you should be able to use `Axis` [`labelProps`](https://vx-demo.now.sh/docs/axis#Axis_labelProps) to set a [`dx` or `dy`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dx) (depending on the orientation) offset for the label. 

This would have to match/account for the `margin` + tickLabel `width` dimensions, something like

```ts
const tickLabelWidth = 50;
const axisLabelOffset = tickLabelWidth + 8;
const marginLeft = axisLabelOffset + axisLabelFontSize;
```

**Comment by samjbmason** [comment]
Perfect! I actually implemented the dynamic max width calculations today! But I think both solutions are great depending on use case!

**Comment by iamyojimbo** [comment]
This is how I got this to work:

**Comment by kristw** [comment]
https://github.com/apache-superset/superset-ui/blob/master/packages/superset-ui-dimension/src/getTextDimension.ts

```ts
import { getTextDimension } from '@superset-ui/dimension';

const { width, height } = getTextDimension({ 
  text: 'your-text',
  style?: ...
  className?: ...
  container?: ...
});
```

@hshoff  @williaster Do you think `vx/responsive` will be interested in having function like above?

**Comment by SagnikPradhan** [comment]
If anybody is having issues with `width` causing the text to not position right and overflow into chart on top, `verticalAnchor` prop exists, set it to `start` :p
