### ISSUE TITLE
Codesandbox demos are not working

### ISSUE THREAD

**Issue by TheBrainTeam** [hshoff/vx#746]
https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-zoom-i

https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-linktypes

**Comment by techniq** [comment]
@TheBrainTeam They are working for me...

![image](https://user-images.githubusercontent.com/177476/84501604-c80a4c00-ac84-11ea-9954-518812b452de.png)

![image](https://user-images.githubusercontent.com/177476/84501546-ae690480-ac84-11ea-8c54-1cb4d15396ad.png)

I had an [issue](https://twitter.com/techniq35/status/1268011919748861953) with Codesandbox a little over a week ago when they changed how they handled modules, but it has been fixed.  Maybe another hiccup?

**Comment by hshoff** [comment]
Also working for me. Without further details it's hard to assist here.
