### ISSUE TITLE
Add tooltip to radar chart

### ISSUE THREAD

**Issue by danzawadzki** [hshoff/vx#747]
Hi 👋, 
I'm trying to add a tooltip to the radar component, but I completely don't know where to start.  What I'm trying to do is to show tooltip on polygon corner hover. First, I have created assistant transparent lines that go through every corner of polygon, but it didn't work well, as area listing on hover should be probably bigger, what is else, I didn't pass `tooltipData` properly.

https://codesandbox.io/s/vxradar-tooltip-veefl
What I've managed to do for the moment. My problem is to:
1. Extend area activeting hover tooltip
2. Pass data correctly to the tooltip hook

What's important I really want to use `useTooltip` hook.

**Comment by williaster** [comment]
Hey @danzawadzki 👋 thanks for checking out `vx`.

To add a tooltip to a chart, you need to  find the closest datum to the mouse event position. there are lots of approaches to this, one of which is using a [voronoi](https://vx-demo.now.sh/docs/voronoi) overlay. Here's an [updated sandbox](https://codesandbox.io/s/vxradar-tooltip-k475y?file=/Example.tsx) with this approach, if you'd like to update our vx demo with this logic I'm sure others would benefit!

Feel free to re-open this if you have more questions.

<img src="https://user-images.githubusercontent.com/4496521/85234703-1fff2c00-b3c4-11ea-87c2-b6efead65f9c.png" width="400" />
