### ISSUE TITLE
withParentSize: add "leading" option to debounced resize handler

### ISSUE THREAD

**Issue by Pringels** [hshoff/vx#753]
Hello 👋,

I noticed that the `withParentSize` HOC introduces an artificial 300ms delay when my component renders on first page load. When setting `debounceTime` manually to something lower like `10` this delay disappears.

While debouncing is obviously a great way to prevent a high frequency re-renders, I do feel user experience is negatively impacted if the chart takes 300ms longer to render than it normally would.

A solution would be to enable the `leading` option for the debounce call. That way the very first invocation will always trigger immediately.

See: https://lodash.com/docs/4.17.15#debounce

I'll gladly submit a PR for this if you're open to the idea

VX ❤️

**Comment by williaster** [comment]
Hey @Pringels 👋 , thanks for checking out `vx`.

I think this would be a reasonable change to make, @hshoff @kristw do you have any concerns?
