### ISSUE TITLE
Stroke Color till source with different color

### ISSUE THREAD

**Issue by Im10Anish** [hshoff/vx#757]
[this](https://vx-demo.now.sh/linktypes) wants to give a different line color to the source.
eg: I'm using status to handle line color so right now if node D has error able to change stroke color of node C to Node D but want this line color till the node T(this will happens only if any Node has error status)

**Comment by hshoff** [comment]
Conditionally changing the stroke of a link is easy. 

```

**Comment by hshoff** [comment]
Conditionally changing a link stroke color is possible. How you want to conditionally change the color is up to you. In the code snippet below if the index is `2` the stroke is blue, else it's red.

```jsx
<Tree>
  {(tree) => {
    return tree.links().map((link, i) => {
      return (
        <LinkComponent
          key={i}
          data={link}
          stroke={i === 2 ? "blue" : "red"}
          strokeWidth="1"
          fill="none"
        />
      );
    });
  }}
</Tree>
```

Hope this helps!

**Comment by Im10Anish** [comment]
Thanks but my question was different sorry that I didn't explain it better before. And conditionally changing line stroke I already able to do. What I am trying to do take this example: 

```Node A -> Node B -> Node C
```
with this snippet, line stroke b/w Node B & Node C is red as Node C has error status and this is working fine.

```<LinkComponent
    data={link}
    percent={+stepPercent}
    stroke={link.target.data.status}
    strokeWidth="1"
    fill="none"
    key={i} 
/>
```
But I want if any node has error status like in this case Node C has then not only line stroke of Node B & C has a red line but Node A & B also i.e till source has same line stroke.

**Comment by techniq** [comment]
@Im10Anish You can use d3-hierarchy's [ancestors](https://github.com/d3/d3-hierarchy#node_ancestors) or [path](https://github.com/d3/d3-hierarchy#node_path) to make this determination on color.

If you look at some of the d3-hierarchy examples [here](https://observablehq.com/@d3/d3-hierarchy), and specifically the handling of `highlight` in their examples, it should get you what you are looking for.
