### ISSUE TITLE
Pie chart with startAngle makes react-spring animations weird

### ISSUE THREAD

**Issue by jithureddy** [hshoff/vx#758]
I was trying to modify the Pie chart example as per my needs as below

- Change the startAngle of Pie to make the top segment in the center.
- Move the label of each pie segment outside and make use of pie.centroid to keep it in center

I notice an issue with weird loading animation with react spring, which is spinning multiple times

**DEMO** - https://codesandbox.io/s/dawn-pond-608v5

I had to remove the animation for now, Please help or any guidance to fix the issue would be helpful

**Comment by hshoff** [comment]
Looks like something is up with your `fromLeaveTransition`. Changing it too:

```jsx
const fromLeaveTransition = ({ startAngle, endAngle }: PieArcDatum<any>) => ({
  startAngle,
  endAngle: startAngle,
  opacity: 0
});
```

Resolves the spinning: https://codesandbox.io/s/empty-snowflake-ilvwf?file=/Example.tsx

If you'd like to reverse the direction:
```jsx
const fromLeaveTransition = ({ startAngle, endAngle }: PieArcDatum<any>) => ({
  startAngle: endAngle,
  endAngle,
  opacity: 0
});
```

Hope this helps!
