### ISSUE TITLE
How to draw a line with a set of points it must go through

### ISSUE THREAD

**Issue by danzawadzki** [hshoff/vx#760]
Hi,
I wonder if I can find a graph/module in the package that will allow me to draw a line with a set of points it must go through.

![image](https://user-images.githubusercontent.com/23190254/86454669-e01f3980-bd1f-11ea-9f1a-16db3eef73d4.png)

The sample data set will look like this:
`const DATA_SET = [[10,20],[30,40],[40,40], [50,40], [50,60]`

None of the values grow uniformly, so it is not possible to use a simple linear chart and hide the x and y axes. This is something arbitrary, where the order of values defines the distribution of points in some space and then connects them with a line. I was thinking maybe @vx/drag will be something that may be helpful, but I'm not really sure.

![image](https://user-images.githubusercontent.com/23190254/86456003-bcf58980-bd21-11ea-88e4-cfed28d84e49.png)
https://vx-demo.now.sh/curves

This graph is potentially very close to what I'm looking for, but I don't know how to solve situations where the next value on the graph goes back on the x-axis.

**Comment by hshoff** [comment]
https://codesandbox.io/s/relaxed-grothendieck-zk5y3?file=/src/App.js

Hope this helps!
