### ISSUE TITLE
Graph won't get shown/rendered!

### ISSUE THREAD

**Issue by TheOnlyArtz** [hshoff/vx#769]
Hey! I'm trying to use VX for my new project and I've followed a tutorial on Medium, for somereason the graph won't get rendered at all!

I'm using the latest versions of VX and Node.
https://codesandbox.io/s/practical-waterfall-m6r7p?file=/src/App.js

EDIT: Removed unnecessary imports

**Comment by hshoff** [comment]
fixed here: https://codesandbox.io/s/recursing-christian-v0r8r?file=/src/App.js

two updates:

1. `scaleTime` expects dates not strings:

    ```diff
    - const x = d => d.date;
    + const x = d => new Date(d.date);
    ```

1. looks like you were using an out of date tutorial that used an older api for [AreaClosed](https://vx-demo.now.sh/docs/shape#AreaClosed)

    ```diff
    <AreaClosed
      data={data}
      yScale={yScale}
    - x={x}
    + x={d => xScale(x(d))}
    - y={y}
    + y={d => yScale(y(d))}
      fill={"green"}
    />
    ```
