### ISSUE TITLE
Bar color change onClick

### ISSUE THREAD

**Issue by alangrn** [hshoff/vx#781]
Are there any examples which show how we can change an individual bars styles onClick?

For example I want the clicked bar to change color.

**Comment by williaster** [comment]
Hey @alangrn 👋 , thanks for checking out `vx`. [Here's a modified sandbox](https://codesandbox.io/s/agitated-shape-04zpj?file=/Example.tsx) of the [Bar demo](https://vx-demo.now.sh/bars) that includes `onClick` style-changing logic. 

Hope it helps!

<img src="https://user-images.githubusercontent.com/4496521/90551511-4d5b2280-e146-11ea-86cf-2a4c1e3c6e6f.png" width="500" />
