### ISSUE TITLE
[docs] document api of all packages

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#9]

**Comment by Flaque** [comment]
Hey, this might be a stupid question, but where's the repo for the docs?

**Comment by hshoff** [comment]
Great question. My current plan is to add docs to each `packages/**/Readme.md` then write a script that builds those to a new dir called `docs/` at the vx repo root. Open to suggestions for alternative solutions!

**Comment by Flaque** [comment]
I looked into [react-docgen](https://github.com/reactjs/react-docgen) a bit for linking docs to code. But react-docgen assumes a `class` structure for it's objects and doesn't really work all that well with the existing code. It might be a future thing, but I'm just gonna write docs in the Readme's for the moment.

**Comment by Flaque** [comment]
Is `brush` "stable"-ish right now? There's no longer a gallery version of it. Should I just hold off on writing the docs on it for now?

**Comment by trainorpj** [comment]
Do you need help writing some of the documentation?  I could submit a PR for the [boxplots](https://github.com/hshoff/vx/tree/master/packages/vx-boxplot) docs, if nobody has that action.

I've been watching this project for a while, and I like it a lot.  I'm interested in helping out, if you'll have me!

**Comment by Flaque** [comment]
Do it! :D

**Comment by williaster** [comment]
closed @trainorpj by https://github.com/hshoff/vx/pull/102

**Comment by williaster** [comment]
🙈 didn't mean to close the entire issue

**Comment by kandros** [comment]
These are the packages with missing documentation

- [ ] brush
- [ ] clip-path
- [ ] brush
- [ ] drag
- [ ] event
- [ ] hierarchy
- [ ] responsive
- [ ] tooltip
- [ ] zoom

**Comment by trainorpj** [comment]
I wrote the docs for the boxplot component, and I'm happy to contribute to other utilities/components

(I was a bit swamped before, but I have some time now)

**Comment by trainorpj** [comment]
I just hacked together a little site we can use to keep track of progress on the docs: 

[https://trainorpj.github.io/vx-docs-progress/](https://trainorpj.github.io/vx-docs-progress/)

I figured there are so many packages/components it'd be nice to keep track of things at a high level.

[Link to the repo](https://github.com/trainorpj/vx-docs-progress/blob/master/README.md). Feel free to make changes.  I used d3 but didn't use vx... 😬

**Comment by hshoff** [comment]
Very helpful, thank @trainorpj! I'm hoping for all green by v1

**Comment by hshoff** [comment]
This should be fixed in: https://github.com/hshoff/vx/pull/399

Need to add descriptions, but at least api doc generation is automated now.
