### ISSUE TITLE
Bug: LinePath doesn't connect if value is 0

### ISSUE THREAD

**Issue by thienanle** [hshoff/vx#99]
![image](https://user-images.githubusercontent.com/874402/28254435-3014c4a8-6af0-11e7-9137-c71900195d2f.png)

**Comment by hshoff** [comment]
Hi @thienanle thanks for checking out vx!

<LinePath /> accepts a `defined` which is a function which defaults to `d => y(d) && x(d)`: https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/LinePath.js#L27 

If you pass in `defined={d => true}` it should work.

Maybe this is a bad default and we should match `d3` default of `() => true`: https://github.com/d3/d3-shape#line_defined

**Comment by thienanle** [comment]
@hshoff thanks for the quick response, that works! Yes I'd agree matching D3's default would be better.

**Comment by hshoff** [comment]
Will update it in the v0.0.131 release. Tracking here https://github.com/hshoff/vx/issues/100
